//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGOFCv3.pideOSF_Sunat {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonaRequest", Namespace="http://schemas.datacontract.org/2004/07/Osinfor.Pide.Request")]
    [System.SerializableAttribute()]
    public partial class PersonaRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApePaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre02Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre03Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char TipoPersonaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeMaterno {
            get {
                return this.ApeMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeMaternoField, value) != true)) {
                    this.ApeMaternoField = value;
                    this.RaisePropertyChanged("ApeMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApePaterno {
            get {
                return this.ApePaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApePaternoField, value) != true)) {
                    this.ApePaternoField = value;
                    this.RaisePropertyChanged("ApePaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre01 {
            get {
                return this.Nombre01Field;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre01Field, value) != true)) {
                    this.Nombre01Field = value;
                    this.RaisePropertyChanged("Nombre01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre02 {
            get {
                return this.Nombre02Field;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre02Field, value) != true)) {
                    this.Nombre02Field = value;
                    this.RaisePropertyChanged("Nombre02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre03 {
            get {
                return this.Nombre03Field;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre03Field, value) != true)) {
                    this.Nombre03Field = value;
                    this.RaisePropertyChanged("Nombre03");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruc {
            get {
                return this.RucField;
            }
            set {
                if ((object.ReferenceEquals(this.RucField, value) != true)) {
                    this.RucField = value;
                    this.RaisePropertyChanged("Ruc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char TipoPersona {
            get {
                return this.TipoPersonaField;
            }
            set {
                if ((this.TipoPersonaField.Equals(value) != true)) {
                    this.TipoPersonaField = value;
                    this.RaisePropertyChanged("TipoPersona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaInfoRequest", Namespace="http://schemas.datacontract.org/2004/07/Osinfor.Pide.Request")]
    [System.SerializableAttribute()]
    public partial class ConsultaInfoRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPTerminalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string App {
            get {
                return this.AppField;
            }
            set {
                if ((object.ReferenceEquals(this.AppField, value) != true)) {
                    this.AppField = value;
                    this.RaisePropertyChanged("App");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPTerminal {
            get {
                return this.IPTerminalField;
            }
            set {
                if ((object.ReferenceEquals(this.IPTerminalField, value) != true)) {
                    this.IPTerminalField = value;
                    this.RaisePropertyChanged("IPTerminal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosRucResponse", Namespace="http://schemas.datacontract.org/2004/07/Osinfor.Pide.Response")]
    [System.SerializableAttribute()]
    public partial class DatosRucResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActividadEconomica_01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActividadEconomica_02Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActividadEconomica_03Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComercioExteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CondicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Correo_01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Correo_02Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomicilioLegalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsHabidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaActualizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaAltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaBajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaConstitucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoBajaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreComunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreViaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SIGOFCv3.pideOSF_Sunat.DatosRucRepLegalResponse[] RepresentanteLegalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Telefono_01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Telefono_02Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Telefono_03Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoContabilidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoViaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActividadEconomica_01 {
            get {
                return this.ActividadEconomica_01Field;
            }
            set {
                if ((object.ReferenceEquals(this.ActividadEconomica_01Field, value) != true)) {
                    this.ActividadEconomica_01Field = value;
                    this.RaisePropertyChanged("ActividadEconomica_01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActividadEconomica_02 {
            get {
                return this.ActividadEconomica_02Field;
            }
            set {
                if ((object.ReferenceEquals(this.ActividadEconomica_02Field, value) != true)) {
                    this.ActividadEconomica_02Field = value;
                    this.RaisePropertyChanged("ActividadEconomica_02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActividadEconomica_03 {
            get {
                return this.ActividadEconomica_03Field;
            }
            set {
                if ((object.ReferenceEquals(this.ActividadEconomica_03Field, value) != true)) {
                    this.ActividadEconomica_03Field = value;
                    this.RaisePropertyChanged("ActividadEconomica_03");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComercioExterior {
            get {
                return this.ComercioExteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.ComercioExteriorField, value) != true)) {
                    this.ComercioExteriorField = value;
                    this.RaisePropertyChanged("ComercioExterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Condicion {
            get {
                return this.CondicionField;
            }
            set {
                if ((object.ReferenceEquals(this.CondicionField, value) != true)) {
                    this.CondicionField = value;
                    this.RaisePropertyChanged("Condicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo_01 {
            get {
                return this.Correo_01Field;
            }
            set {
                if ((object.ReferenceEquals(this.Correo_01Field, value) != true)) {
                    this.Correo_01Field = value;
                    this.RaisePropertyChanged("Correo_01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo_02 {
            get {
                return this.Correo_02Field;
            }
            set {
                if ((object.ReferenceEquals(this.Correo_02Field, value) != true)) {
                    this.Correo_02Field = value;
                    this.RaisePropertyChanged("Correo_02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DomicilioLegal {
            get {
                return this.DomicilioLegalField;
            }
            set {
                if ((object.ReferenceEquals(this.DomicilioLegalField, value) != true)) {
                    this.DomicilioLegalField = value;
                    this.RaisePropertyChanged("DomicilioLegal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsActivo {
            get {
                return this.EsActivoField;
            }
            set {
                if ((this.EsActivoField.Equals(value) != true)) {
                    this.EsActivoField = value;
                    this.RaisePropertyChanged("EsActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsHabido {
            get {
                return this.EsHabidoField;
            }
            set {
                if ((this.EsHabidoField.Equals(value) != true)) {
                    this.EsHabidoField = value;
                    this.RaisePropertyChanged("EsHabido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaActualizacion {
            get {
                return this.FechaActualizacionField;
            }
            set {
                if ((this.FechaActualizacionField.Equals(value) != true)) {
                    this.FechaActualizacionField = value;
                    this.RaisePropertyChanged("FechaActualizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaAlta {
            get {
                return this.FechaAltaField;
            }
            set {
                if ((this.FechaAltaField.Equals(value) != true)) {
                    this.FechaAltaField = value;
                    this.RaisePropertyChanged("FechaAlta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaBaja {
            get {
                return this.FechaBajaField;
            }
            set {
                if ((this.FechaBajaField.Equals(value) != true)) {
                    this.FechaBajaField = value;
                    this.RaisePropertyChanged("FechaBaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaConstitucion {
            get {
                return this.FechaConstitucionField;
            }
            set {
                if ((this.FechaConstitucionField.Equals(value) != true)) {
                    this.FechaConstitucionField = value;
                    this.RaisePropertyChanged("FechaConstitucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotivoBaja {
            get {
                return this.MotivoBajaField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoBajaField, value) != true)) {
                    this.MotivoBajaField = value;
                    this.RaisePropertyChanged("MotivoBaja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreComun {
            get {
                return this.NombreComunField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreComunField, value) != true)) {
                    this.NombreComunField = value;
                    this.RaisePropertyChanged("NombreComun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreVia {
            get {
                return this.NombreViaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreViaField, value) != true)) {
                    this.NombreViaField = value;
                    this.RaisePropertyChanged("NombreVia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Registro {
            get {
                return this.RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistroField, value) != true)) {
                    this.RegistroField = value;
                    this.RaisePropertyChanged("Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SIGOFCv3.pideOSF_Sunat.DatosRucRepLegalResponse[] RepresentanteLegal {
            get {
                return this.RepresentanteLegalField;
            }
            set {
                if ((object.ReferenceEquals(this.RepresentanteLegalField, value) != true)) {
                    this.RepresentanteLegalField = value;
                    this.RaisePropertyChanged("RepresentanteLegal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono_01 {
            get {
                return this.Telefono_01Field;
            }
            set {
                if ((object.ReferenceEquals(this.Telefono_01Field, value) != true)) {
                    this.Telefono_01Field = value;
                    this.RaisePropertyChanged("Telefono_01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono_02 {
            get {
                return this.Telefono_02Field;
            }
            set {
                if ((object.ReferenceEquals(this.Telefono_02Field, value) != true)) {
                    this.Telefono_02Field = value;
                    this.RaisePropertyChanged("Telefono_02");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono_03 {
            get {
                return this.Telefono_03Field;
            }
            set {
                if ((object.ReferenceEquals(this.Telefono_03Field, value) != true)) {
                    this.Telefono_03Field = value;
                    this.RaisePropertyChanged("Telefono_03");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoContabilidad {
            get {
                return this.TipoContabilidadField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoContabilidadField, value) != true)) {
                    this.TipoContabilidadField = value;
                    this.RaisePropertyChanged("TipoContabilidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoEmpresa {
            get {
                return this.TipoEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoEmpresaField, value) != true)) {
                    this.TipoEmpresaField = value;
                    this.RaisePropertyChanged("TipoEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPersona {
            get {
                return this.TipoPersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPersonaField, value) != true)) {
                    this.TipoPersonaField = value;
                    this.RaisePropertyChanged("TipoPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoVia {
            get {
                return this.TipoViaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoViaField, value) != true)) {
                    this.TipoViaField = value;
                    this.RaisePropertyChanged("TipoVia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosRucRepLegalResponse", Namespace="http://schemas.datacontract.org/2004/07/Osinfor.Pide.Response")]
    [System.SerializableAttribute()]
    public partial class DatosRucRepLegalResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaActualizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaInicioVigenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescDocumento {
            get {
                return this.DescDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescDocumentoField, value) != true)) {
                    this.DescDocumentoField = value;
                    this.RaisePropertyChanged("DescDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaActualizacion {
            get {
                return this.FechaActualizacionField;
            }
            set {
                if ((this.FechaActualizacionField.Equals(value) != true)) {
                    this.FechaActualizacionField = value;
                    this.RaisePropertyChanged("FechaActualizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInicioVigencia {
            get {
                return this.FechaInicioVigenciaField;
            }
            set {
                if ((this.FechaInicioVigenciaField.Equals(value) != true)) {
                    this.FechaInicioVigenciaField = value;
                    this.RaisePropertyChanged("FechaInicioVigencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroDocumento {
            get {
                return this.NroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NroDocumentoField, value) != true)) {
                    this.NroDocumentoField = value;
                    this.RaisePropertyChanged("NroDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="pideOSF_Sunat.ISunatService")]
    public interface ISunatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISunatService/ConsultaRuc", ReplyAction="http://tempuri.org/ISunatService/ConsultaRucResponse")]
        SIGOFCv3.pideOSF_Sunat.DatosRucResponse ConsultaRuc(SIGOFCv3.pideOSF_Sunat.PersonaRequest personaRequest, SIGOFCv3.pideOSF_Sunat.ConsultaInfoRequest consultaRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISunatService/ConsultaRuc", ReplyAction="http://tempuri.org/ISunatService/ConsultaRucResponse")]
        System.Threading.Tasks.Task<SIGOFCv3.pideOSF_Sunat.DatosRucResponse> ConsultaRucAsync(SIGOFCv3.pideOSF_Sunat.PersonaRequest personaRequest, SIGOFCv3.pideOSF_Sunat.ConsultaInfoRequest consultaRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISunatServiceChannel : SIGOFCv3.pideOSF_Sunat.ISunatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SunatServiceClient : System.ServiceModel.ClientBase<SIGOFCv3.pideOSF_Sunat.ISunatService>, SIGOFCv3.pideOSF_Sunat.ISunatService {
        
        public SunatServiceClient() {
        }
        
        public SunatServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SunatServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SunatServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SunatServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SIGOFCv3.pideOSF_Sunat.DatosRucResponse ConsultaRuc(SIGOFCv3.pideOSF_Sunat.PersonaRequest personaRequest, SIGOFCv3.pideOSF_Sunat.ConsultaInfoRequest consultaRequest) {
            return base.Channel.ConsultaRuc(personaRequest, consultaRequest);
        }
        
        public System.Threading.Tasks.Task<SIGOFCv3.pideOSF_Sunat.DatosRucResponse> ConsultaRucAsync(SIGOFCv3.pideOSF_Sunat.PersonaRequest personaRequest, SIGOFCv3.pideOSF_Sunat.ConsultaInfoRequest consultaRequest) {
            return base.Channel.ConsultaRucAsync(personaRequest, consultaRequest);
        }
    }
}
