//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGOFCv3.sigoWSSupervision {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/webservices/", ConfigurationName="sigoWSSupervision.WSSupervisionSoap")]
    public interface WSSupervisionSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje listaCNotificacionesRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/listaCNotificaciones", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SIGOFCv3.sigoWSSupervision.listaCNotificacionesResponse listaCNotificaciones(SIGOFCv3.sigoWSSupervision.listaCNotificacionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/listaCNotificaciones", ReplyAction="*")]
        System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.listaCNotificacionesResponse> listaCNotificacionesAsync(SIGOFCv3.sigoWSSupervision.listaCNotificacionesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje listaInformesRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/listaInformes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SIGOFCv3.sigoWSSupervision.listaInformesResponse listaInformes(SIGOFCv3.sigoWSSupervision.listaInformesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/listaInformes", ReplyAction="*")]
        System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.listaInformesResponse> listaInformesAsync(SIGOFCv3.sigoWSSupervision.listaInformesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje listaMuestraRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/listaMuestra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SIGOFCv3.sigoWSSupervision.listaMuestraResponse listaMuestra(SIGOFCv3.sigoWSSupervision.listaMuestraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/listaMuestra", ReplyAction="*")]
        System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.listaMuestraResponse> listaMuestraAsync(SIGOFCv3.sigoWSSupervision.listaMuestraRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje cargaDatosCampoMaderableRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/cargaDatosCampoMaderable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SIGOFCv3.sigoWSSupervision.cargaDatosCampoMaderableResponse cargaDatosCampoMaderable(SIGOFCv3.sigoWSSupervision.cargaDatosCampoMaderableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/cargaDatosCampoMaderable", ReplyAction="*")]
        System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.cargaDatosCampoMaderableResponse> cargaDatosCampoMaderableAsync(SIGOFCv3.sigoWSSupervision.cargaDatosCampoMaderableRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje cargaDatosCampoNoMaderableRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/cargaDatosCampoNoMaderable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SIGOFCv3.sigoWSSupervision.cargaDatosCampoNoMaderableResponse cargaDatosCampoNoMaderable(SIGOFCv3.sigoWSSupervision.cargaDatosCampoNoMaderableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/cargaDatosCampoNoMaderable", ReplyAction="*")]
        System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.cargaDatosCampoNoMaderableResponse> cargaDatosCampoNoMaderableAsync(SIGOFCv3.sigoWSSupervision.cargaDatosCampoNoMaderableRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje listaEspNCientificoRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/listaEspNCientifico", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SIGOFCv3.sigoWSSupervision.listaEspNCientificoResponse listaEspNCientifico(SIGOFCv3.sigoWSSupervision.listaEspNCientificoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/listaEspNCientifico", ReplyAction="*")]
        System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.listaEspNCientificoResponse> listaEspNCientificoAsync(SIGOFCv3.sigoWSSupervision.listaEspNCientificoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje listaEspNComunRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/listaEspNComun", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SIGOFCv3.sigoWSSupervision.listaEspNComunResponse listaEspNComun(SIGOFCv3.sigoWSSupervision.listaEspNComunRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/listaEspNComun", ReplyAction="*")]
        System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.listaEspNComunResponse> listaEspNComunAsync(SIGOFCv3.sigoWSSupervision.listaEspNComunRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje listaDatosPOAsRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/listaDatosPOAs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SIGOFCv3.sigoWSSupervision.listaDatosPOAsResponse listaDatosPOAs(SIGOFCv3.sigoWSSupervision.listaDatosPOAsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/listaDatosPOAs", ReplyAction="*")]
        System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.listaDatosPOAsResponse> listaDatosPOAsAsync(SIGOFCv3.sigoWSSupervision.listaDatosPOAsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje listaDatosPOAs_v3Request tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/listaDatosPOAs_v3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SIGOFCv3.sigoWSSupervision.listaDatosPOAs_v3Response listaDatosPOAs_v3(SIGOFCv3.sigoWSSupervision.listaDatosPOAs_v3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/listaDatosPOAs_v3", ReplyAction="*")]
        System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.listaDatosPOAs_v3Response> listaDatosPOAs_v3Async(SIGOFCv3.sigoWSSupervision.listaDatosPOAs_v3Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class autenticaUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class objNoMaderable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cOD_INFORMEField;
        
        private string cOD_SISTEMAField;
        
        private string cOD_ESPECIES_CAMPOField;
        
        private string eSPECIES_NCIENTIFICOField;
        
        private string eSPECIES_NCOMUNField;
        
        private int cOD_SECUENCIALField;
        
        private string nUM_ESTRADAField;
        
        private string cODIGOField;
        
        private decimal dIAMETROField;
        
        private decimal aLTURAField;
        
        private decimal pRODUCCION_LATASField;
        
        private string zONAField;
        
        private int cOORDENADA_ESTEField;
        
        private int cOORDENADA_NORTEField;
        
        private string cOD_EESTADOField;
        
        private string cONDICION_CAMPOField;
        
        private string eSTADO_CAMPOField;
        
        private int nUM_COCOS_ABIERTOSField;
        
        private int nUM_COCOS_CERRADOSField;
        
        private string oBSERVACION_CAMPOField;
        
        private string cOD_EFITOSANITARIOField;
        
        private string cOD_CFUSTEField;
        
        private string cOD_FCOPAField;
        
        private string cOD_PCOPAField;
        
        private string cOD_EFENOLOGICOField;
        
        private string cOD_ESANITARIOField;
        
        private string cOD_ILIANASField;
        
        private string dESC_CFUSTEField;
        
        private string dESC_PCOPAField;
        
        private string dESC_FCOPAField;
        
        private string dESC_EFENOLOGICOField;
        
        private string dESC_ESANITARIOField;
        
        private string dESC_ILIANASField;
        
        private string eSTADO_SUPERVISIONField;
        
        private int regEstadoField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string COD_INFORME {
            get {
                return this.cOD_INFORMEField;
            }
            set {
                this.cOD_INFORMEField = value;
                this.RaisePropertyChanged("COD_INFORME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string COD_SISTEMA {
            get {
                return this.cOD_SISTEMAField;
            }
            set {
                this.cOD_SISTEMAField = value;
                this.RaisePropertyChanged("COD_SISTEMA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string COD_ESPECIES_CAMPO {
            get {
                return this.cOD_ESPECIES_CAMPOField;
            }
            set {
                this.cOD_ESPECIES_CAMPOField = value;
                this.RaisePropertyChanged("COD_ESPECIES_CAMPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ESPECIES_NCIENTIFICO {
            get {
                return this.eSPECIES_NCIENTIFICOField;
            }
            set {
                this.eSPECIES_NCIENTIFICOField = value;
                this.RaisePropertyChanged("ESPECIES_NCIENTIFICO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ESPECIES_NCOMUN {
            get {
                return this.eSPECIES_NCOMUNField;
            }
            set {
                this.eSPECIES_NCOMUNField = value;
                this.RaisePropertyChanged("ESPECIES_NCOMUN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int COD_SECUENCIAL {
            get {
                return this.cOD_SECUENCIALField;
            }
            set {
                this.cOD_SECUENCIALField = value;
                this.RaisePropertyChanged("COD_SECUENCIAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NUM_ESTRADA {
            get {
                return this.nUM_ESTRADAField;
            }
            set {
                this.nUM_ESTRADAField = value;
                this.RaisePropertyChanged("NUM_ESTRADA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CODIGO {
            get {
                return this.cODIGOField;
            }
            set {
                this.cODIGOField = value;
                this.RaisePropertyChanged("CODIGO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal DIAMETRO {
            get {
                return this.dIAMETROField;
            }
            set {
                this.dIAMETROField = value;
                this.RaisePropertyChanged("DIAMETRO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal ALTURA {
            get {
                return this.aLTURAField;
            }
            set {
                this.aLTURAField = value;
                this.RaisePropertyChanged("ALTURA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal PRODUCCION_LATAS {
            get {
                return this.pRODUCCION_LATASField;
            }
            set {
                this.pRODUCCION_LATASField = value;
                this.RaisePropertyChanged("PRODUCCION_LATAS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ZONA {
            get {
                return this.zONAField;
            }
            set {
                this.zONAField = value;
                this.RaisePropertyChanged("ZONA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int COORDENADA_ESTE {
            get {
                return this.cOORDENADA_ESTEField;
            }
            set {
                this.cOORDENADA_ESTEField = value;
                this.RaisePropertyChanged("COORDENADA_ESTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int COORDENADA_NORTE {
            get {
                return this.cOORDENADA_NORTEField;
            }
            set {
                this.cOORDENADA_NORTEField = value;
                this.RaisePropertyChanged("COORDENADA_NORTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string COD_EESTADO {
            get {
                return this.cOD_EESTADOField;
            }
            set {
                this.cOD_EESTADOField = value;
                this.RaisePropertyChanged("COD_EESTADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CONDICION_CAMPO {
            get {
                return this.cONDICION_CAMPOField;
            }
            set {
                this.cONDICION_CAMPOField = value;
                this.RaisePropertyChanged("CONDICION_CAMPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ESTADO_CAMPO {
            get {
                return this.eSTADO_CAMPOField;
            }
            set {
                this.eSTADO_CAMPOField = value;
                this.RaisePropertyChanged("ESTADO_CAMPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int NUM_COCOS_ABIERTOS {
            get {
                return this.nUM_COCOS_ABIERTOSField;
            }
            set {
                this.nUM_COCOS_ABIERTOSField = value;
                this.RaisePropertyChanged("NUM_COCOS_ABIERTOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int NUM_COCOS_CERRADOS {
            get {
                return this.nUM_COCOS_CERRADOSField;
            }
            set {
                this.nUM_COCOS_CERRADOSField = value;
                this.RaisePropertyChanged("NUM_COCOS_CERRADOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string OBSERVACION_CAMPO {
            get {
                return this.oBSERVACION_CAMPOField;
            }
            set {
                this.oBSERVACION_CAMPOField = value;
                this.RaisePropertyChanged("OBSERVACION_CAMPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string COD_EFITOSANITARIO {
            get {
                return this.cOD_EFITOSANITARIOField;
            }
            set {
                this.cOD_EFITOSANITARIOField = value;
                this.RaisePropertyChanged("COD_EFITOSANITARIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string COD_CFUSTE {
            get {
                return this.cOD_CFUSTEField;
            }
            set {
                this.cOD_CFUSTEField = value;
                this.RaisePropertyChanged("COD_CFUSTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string COD_FCOPA {
            get {
                return this.cOD_FCOPAField;
            }
            set {
                this.cOD_FCOPAField = value;
                this.RaisePropertyChanged("COD_FCOPA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string COD_PCOPA {
            get {
                return this.cOD_PCOPAField;
            }
            set {
                this.cOD_PCOPAField = value;
                this.RaisePropertyChanged("COD_PCOPA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string COD_EFENOLOGICO {
            get {
                return this.cOD_EFENOLOGICOField;
            }
            set {
                this.cOD_EFENOLOGICOField = value;
                this.RaisePropertyChanged("COD_EFENOLOGICO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string COD_ESANITARIO {
            get {
                return this.cOD_ESANITARIOField;
            }
            set {
                this.cOD_ESANITARIOField = value;
                this.RaisePropertyChanged("COD_ESANITARIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string COD_ILIANAS {
            get {
                return this.cOD_ILIANASField;
            }
            set {
                this.cOD_ILIANASField = value;
                this.RaisePropertyChanged("COD_ILIANAS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string DESC_CFUSTE {
            get {
                return this.dESC_CFUSTEField;
            }
            set {
                this.dESC_CFUSTEField = value;
                this.RaisePropertyChanged("DESC_CFUSTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string DESC_PCOPA {
            get {
                return this.dESC_PCOPAField;
            }
            set {
                this.dESC_PCOPAField = value;
                this.RaisePropertyChanged("DESC_PCOPA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string DESC_FCOPA {
            get {
                return this.dESC_FCOPAField;
            }
            set {
                this.dESC_FCOPAField = value;
                this.RaisePropertyChanged("DESC_FCOPA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string DESC_EFENOLOGICO {
            get {
                return this.dESC_EFENOLOGICOField;
            }
            set {
                this.dESC_EFENOLOGICOField = value;
                this.RaisePropertyChanged("DESC_EFENOLOGICO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string DESC_ESANITARIO {
            get {
                return this.dESC_ESANITARIOField;
            }
            set {
                this.dESC_ESANITARIOField = value;
                this.RaisePropertyChanged("DESC_ESANITARIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string DESC_ILIANAS {
            get {
                return this.dESC_ILIANASField;
            }
            set {
                this.dESC_ILIANASField = value;
                this.RaisePropertyChanged("DESC_ILIANAS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string ESTADO_SUPERVISION {
            get {
                return this.eSTADO_SUPERVISIONField;
            }
            set {
                this.eSTADO_SUPERVISIONField = value;
                this.RaisePropertyChanged("ESTADO_SUPERVISION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public int RegEstado {
            get {
                return this.regEstadoField;
            }
            set {
                this.regEstadoField = value;
                this.RaisePropertyChanged("RegEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class objMaderable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cOD_INFORMEField;
        
        private string cOD_SISTEMAField;
        
        private string cOD_ESPECIES_CAMPOField;
        
        private string eSPECIES_NCIENTIFICOField;
        
        private string eSPECIES_NCOMUNField;
        
        private string bLOQUE_CAMPOField;
        
        private string fAJA_CAMPOField;
        
        private string cODIGO_CAMPOField;
        
        private decimal dAP_CAMPOField;
        
        private decimal aC_CAMPOField;
        
        private string zONA_CAMPOField;
        
        private int cOORDENADA_ESTE_CAMPOField;
        
        private int cOORDENADA_NORTE_CAMPOField;
        
        private string cOD_EESTADOField;
        
        private string eSTADO_CAMPOField;
        
        private string oBSERVACION_CAMPOField;
        
        private string cOD_CFUSTEField;
        
        private string cOD_FCOPAField;
        
        private string cOD_PCOPAField;
        
        private string cOD_EFENOLOGICOField;
        
        private string cOD_ESANITARIOField;
        
        private string cOD_ILIANASField;
        
        private string dESC_CFUSTEField;
        
        private string dESC_PCOPAField;
        
        private string dESC_FCOPAField;
        
        private string dESC_EFENOLOGICOField;
        
        private string dESC_ESANITARIOField;
        
        private string dESC_ILIANASField;
        
        private decimal bS_ALTURA_TOTALField;
        
        private decimal bS_DIAMETRO_RAMA_1Field;
        
        private decimal bS_DIAMETRO_RAMA_2Field;
        
        private decimal bS_DIAMETRO_RAMA_3Field;
        
        private decimal bS_DIAMETRO_RAMA_4Field;
        
        private decimal bS_DIAMETRO_RAMA_5Field;
        
        private decimal bS_DIAMETRO_RAMA_6Field;
        
        private decimal bS_DIAMETRO_RAMA_7Field;
        
        private decimal bS_LONGITUD_RAMA_1Field;
        
        private decimal bS_LONGITUD_RAMA_2Field;
        
        private decimal bS_LONGITUD_RAMA_3Field;
        
        private decimal bS_LONGITUD_RAMA_4Field;
        
        private decimal bS_LONGITUD_RAMA_5Field;
        
        private decimal bS_LONGITUD_RAMA_6Field;
        
        private decimal bS_LONGITUD_RAMA_7Field;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string COD_INFORME {
            get {
                return this.cOD_INFORMEField;
            }
            set {
                this.cOD_INFORMEField = value;
                this.RaisePropertyChanged("COD_INFORME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string COD_SISTEMA {
            get {
                return this.cOD_SISTEMAField;
            }
            set {
                this.cOD_SISTEMAField = value;
                this.RaisePropertyChanged("COD_SISTEMA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string COD_ESPECIES_CAMPO {
            get {
                return this.cOD_ESPECIES_CAMPOField;
            }
            set {
                this.cOD_ESPECIES_CAMPOField = value;
                this.RaisePropertyChanged("COD_ESPECIES_CAMPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ESPECIES_NCIENTIFICO {
            get {
                return this.eSPECIES_NCIENTIFICOField;
            }
            set {
                this.eSPECIES_NCIENTIFICOField = value;
                this.RaisePropertyChanged("ESPECIES_NCIENTIFICO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ESPECIES_NCOMUN {
            get {
                return this.eSPECIES_NCOMUNField;
            }
            set {
                this.eSPECIES_NCOMUNField = value;
                this.RaisePropertyChanged("ESPECIES_NCOMUN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BLOQUE_CAMPO {
            get {
                return this.bLOQUE_CAMPOField;
            }
            set {
                this.bLOQUE_CAMPOField = value;
                this.RaisePropertyChanged("BLOQUE_CAMPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FAJA_CAMPO {
            get {
                return this.fAJA_CAMPOField;
            }
            set {
                this.fAJA_CAMPOField = value;
                this.RaisePropertyChanged("FAJA_CAMPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CODIGO_CAMPO {
            get {
                return this.cODIGO_CAMPOField;
            }
            set {
                this.cODIGO_CAMPOField = value;
                this.RaisePropertyChanged("CODIGO_CAMPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal DAP_CAMPO {
            get {
                return this.dAP_CAMPOField;
            }
            set {
                this.dAP_CAMPOField = value;
                this.RaisePropertyChanged("DAP_CAMPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal AC_CAMPO {
            get {
                return this.aC_CAMPOField;
            }
            set {
                this.aC_CAMPOField = value;
                this.RaisePropertyChanged("AC_CAMPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ZONA_CAMPO {
            get {
                return this.zONA_CAMPOField;
            }
            set {
                this.zONA_CAMPOField = value;
                this.RaisePropertyChanged("ZONA_CAMPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int COORDENADA_ESTE_CAMPO {
            get {
                return this.cOORDENADA_ESTE_CAMPOField;
            }
            set {
                this.cOORDENADA_ESTE_CAMPOField = value;
                this.RaisePropertyChanged("COORDENADA_ESTE_CAMPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int COORDENADA_NORTE_CAMPO {
            get {
                return this.cOORDENADA_NORTE_CAMPOField;
            }
            set {
                this.cOORDENADA_NORTE_CAMPOField = value;
                this.RaisePropertyChanged("COORDENADA_NORTE_CAMPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string COD_EESTADO {
            get {
                return this.cOD_EESTADOField;
            }
            set {
                this.cOD_EESTADOField = value;
                this.RaisePropertyChanged("COD_EESTADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ESTADO_CAMPO {
            get {
                return this.eSTADO_CAMPOField;
            }
            set {
                this.eSTADO_CAMPOField = value;
                this.RaisePropertyChanged("ESTADO_CAMPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string OBSERVACION_CAMPO {
            get {
                return this.oBSERVACION_CAMPOField;
            }
            set {
                this.oBSERVACION_CAMPOField = value;
                this.RaisePropertyChanged("OBSERVACION_CAMPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string COD_CFUSTE {
            get {
                return this.cOD_CFUSTEField;
            }
            set {
                this.cOD_CFUSTEField = value;
                this.RaisePropertyChanged("COD_CFUSTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string COD_FCOPA {
            get {
                return this.cOD_FCOPAField;
            }
            set {
                this.cOD_FCOPAField = value;
                this.RaisePropertyChanged("COD_FCOPA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string COD_PCOPA {
            get {
                return this.cOD_PCOPAField;
            }
            set {
                this.cOD_PCOPAField = value;
                this.RaisePropertyChanged("COD_PCOPA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string COD_EFENOLOGICO {
            get {
                return this.cOD_EFENOLOGICOField;
            }
            set {
                this.cOD_EFENOLOGICOField = value;
                this.RaisePropertyChanged("COD_EFENOLOGICO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string COD_ESANITARIO {
            get {
                return this.cOD_ESANITARIOField;
            }
            set {
                this.cOD_ESANITARIOField = value;
                this.RaisePropertyChanged("COD_ESANITARIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string COD_ILIANAS {
            get {
                return this.cOD_ILIANASField;
            }
            set {
                this.cOD_ILIANASField = value;
                this.RaisePropertyChanged("COD_ILIANAS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string DESC_CFUSTE {
            get {
                return this.dESC_CFUSTEField;
            }
            set {
                this.dESC_CFUSTEField = value;
                this.RaisePropertyChanged("DESC_CFUSTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string DESC_PCOPA {
            get {
                return this.dESC_PCOPAField;
            }
            set {
                this.dESC_PCOPAField = value;
                this.RaisePropertyChanged("DESC_PCOPA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string DESC_FCOPA {
            get {
                return this.dESC_FCOPAField;
            }
            set {
                this.dESC_FCOPAField = value;
                this.RaisePropertyChanged("DESC_FCOPA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string DESC_EFENOLOGICO {
            get {
                return this.dESC_EFENOLOGICOField;
            }
            set {
                this.dESC_EFENOLOGICOField = value;
                this.RaisePropertyChanged("DESC_EFENOLOGICO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string DESC_ESANITARIO {
            get {
                return this.dESC_ESANITARIOField;
            }
            set {
                this.dESC_ESANITARIOField = value;
                this.RaisePropertyChanged("DESC_ESANITARIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string DESC_ILIANAS {
            get {
                return this.dESC_ILIANASField;
            }
            set {
                this.dESC_ILIANASField = value;
                this.RaisePropertyChanged("DESC_ILIANAS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public decimal BS_ALTURA_TOTAL {
            get {
                return this.bS_ALTURA_TOTALField;
            }
            set {
                this.bS_ALTURA_TOTALField = value;
                this.RaisePropertyChanged("BS_ALTURA_TOTAL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public decimal BS_DIAMETRO_RAMA_1 {
            get {
                return this.bS_DIAMETRO_RAMA_1Field;
            }
            set {
                this.bS_DIAMETRO_RAMA_1Field = value;
                this.RaisePropertyChanged("BS_DIAMETRO_RAMA_1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public decimal BS_DIAMETRO_RAMA_2 {
            get {
                return this.bS_DIAMETRO_RAMA_2Field;
            }
            set {
                this.bS_DIAMETRO_RAMA_2Field = value;
                this.RaisePropertyChanged("BS_DIAMETRO_RAMA_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public decimal BS_DIAMETRO_RAMA_3 {
            get {
                return this.bS_DIAMETRO_RAMA_3Field;
            }
            set {
                this.bS_DIAMETRO_RAMA_3Field = value;
                this.RaisePropertyChanged("BS_DIAMETRO_RAMA_3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public decimal BS_DIAMETRO_RAMA_4 {
            get {
                return this.bS_DIAMETRO_RAMA_4Field;
            }
            set {
                this.bS_DIAMETRO_RAMA_4Field = value;
                this.RaisePropertyChanged("BS_DIAMETRO_RAMA_4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public decimal BS_DIAMETRO_RAMA_5 {
            get {
                return this.bS_DIAMETRO_RAMA_5Field;
            }
            set {
                this.bS_DIAMETRO_RAMA_5Field = value;
                this.RaisePropertyChanged("BS_DIAMETRO_RAMA_5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public decimal BS_DIAMETRO_RAMA_6 {
            get {
                return this.bS_DIAMETRO_RAMA_6Field;
            }
            set {
                this.bS_DIAMETRO_RAMA_6Field = value;
                this.RaisePropertyChanged("BS_DIAMETRO_RAMA_6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public decimal BS_DIAMETRO_RAMA_7 {
            get {
                return this.bS_DIAMETRO_RAMA_7Field;
            }
            set {
                this.bS_DIAMETRO_RAMA_7Field = value;
                this.RaisePropertyChanged("BS_DIAMETRO_RAMA_7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public decimal BS_LONGITUD_RAMA_1 {
            get {
                return this.bS_LONGITUD_RAMA_1Field;
            }
            set {
                this.bS_LONGITUD_RAMA_1Field = value;
                this.RaisePropertyChanged("BS_LONGITUD_RAMA_1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public decimal BS_LONGITUD_RAMA_2 {
            get {
                return this.bS_LONGITUD_RAMA_2Field;
            }
            set {
                this.bS_LONGITUD_RAMA_2Field = value;
                this.RaisePropertyChanged("BS_LONGITUD_RAMA_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public decimal BS_LONGITUD_RAMA_3 {
            get {
                return this.bS_LONGITUD_RAMA_3Field;
            }
            set {
                this.bS_LONGITUD_RAMA_3Field = value;
                this.RaisePropertyChanged("BS_LONGITUD_RAMA_3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public decimal BS_LONGITUD_RAMA_4 {
            get {
                return this.bS_LONGITUD_RAMA_4Field;
            }
            set {
                this.bS_LONGITUD_RAMA_4Field = value;
                this.RaisePropertyChanged("BS_LONGITUD_RAMA_4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public decimal BS_LONGITUD_RAMA_5 {
            get {
                return this.bS_LONGITUD_RAMA_5Field;
            }
            set {
                this.bS_LONGITUD_RAMA_5Field = value;
                this.RaisePropertyChanged("BS_LONGITUD_RAMA_5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public decimal BS_LONGITUD_RAMA_6 {
            get {
                return this.bS_LONGITUD_RAMA_6Field;
            }
            set {
                this.bS_LONGITUD_RAMA_6Field = value;
                this.RaisePropertyChanged("BS_LONGITUD_RAMA_6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public decimal BS_LONGITUD_RAMA_7 {
            get {
                return this.bS_LONGITUD_RAMA_7Field;
            }
            set {
                this.bS_LONGITUD_RAMA_7Field = value;
                this.RaisePropertyChanged("BS_LONGITUD_RAMA_7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaCNotificaciones", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class listaCNotificacionesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://microsoft.com/webservices/")]
        public SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser;
        
        public listaCNotificacionesRequest() {
        }
        
        public listaCNotificacionesRequest(SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser) {
            this.autenticaUser = autenticaUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaCNotificacionesResponse", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class listaCNotificacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string listaCNotificacionesResult;
        
        public listaCNotificacionesResponse() {
        }
        
        public listaCNotificacionesResponse(string listaCNotificacionesResult) {
            this.listaCNotificacionesResult = listaCNotificacionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaInformes", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class listaInformesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://microsoft.com/webservices/")]
        public SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser;
        
        public listaInformesRequest() {
        }
        
        public listaInformesRequest(SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser) {
            this.autenticaUser = autenticaUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaInformesResponse", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class listaInformesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string listaInformesResult;
        
        public listaInformesResponse() {
        }
        
        public listaInformesResponse(string listaInformesResult) {
            this.listaInformesResult = listaInformesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaMuestra", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class listaMuestraRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://microsoft.com/webservices/")]
        public SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string codCN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=1)]
        public string tipo;
        
        public listaMuestraRequest() {
        }
        
        public listaMuestraRequest(SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser, string codCN, string tipo) {
            this.autenticaUser = autenticaUser;
            this.codCN = codCN;
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaMuestraResponse", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class listaMuestraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string listaMuestraResult;
        
        public listaMuestraResponse() {
        }
        
        public listaMuestraResponse(string listaMuestraResult) {
            this.listaMuestraResult = listaMuestraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cargaDatosCampoMaderable", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class cargaDatosCampoMaderableRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://microsoft.com/webservices/")]
        public SIGOFCv3.sigoWSSupervision.objMaderable objMaderable;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://microsoft.com/webservices/")]
        public SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser;
        
        public cargaDatosCampoMaderableRequest() {
        }
        
        public cargaDatosCampoMaderableRequest(SIGOFCv3.sigoWSSupervision.objMaderable objMaderable, SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser) {
            this.objMaderable = objMaderable;
            this.autenticaUser = autenticaUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cargaDatosCampoMaderableResponse", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class cargaDatosCampoMaderableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string cargaDatosCampoMaderableResult;
        
        public cargaDatosCampoMaderableResponse() {
        }
        
        public cargaDatosCampoMaderableResponse(string cargaDatosCampoMaderableResult) {
            this.cargaDatosCampoMaderableResult = cargaDatosCampoMaderableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cargaDatosCampoNoMaderable", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class cargaDatosCampoNoMaderableRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://microsoft.com/webservices/")]
        public SIGOFCv3.sigoWSSupervision.objNoMaderable objNoMaderable;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://microsoft.com/webservices/")]
        public SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser;
        
        public cargaDatosCampoNoMaderableRequest() {
        }
        
        public cargaDatosCampoNoMaderableRequest(SIGOFCv3.sigoWSSupervision.objNoMaderable objNoMaderable, SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser) {
            this.objNoMaderable = objNoMaderable;
            this.autenticaUser = autenticaUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cargaDatosCampoNoMaderableResponse", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class cargaDatosCampoNoMaderableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string cargaDatosCampoNoMaderableResult;
        
        public cargaDatosCampoNoMaderableResponse() {
        }
        
        public cargaDatosCampoNoMaderableResponse(string cargaDatosCampoNoMaderableResult) {
            this.cargaDatosCampoNoMaderableResult = cargaDatosCampoNoMaderableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaEspNCientifico", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class listaEspNCientificoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://microsoft.com/webservices/")]
        public SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser;
        
        public listaEspNCientificoRequest() {
        }
        
        public listaEspNCientificoRequest(SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser) {
            this.autenticaUser = autenticaUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaEspNCientificoResponse", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class listaEspNCientificoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string listaEspNCientificoResult;
        
        public listaEspNCientificoResponse() {
        }
        
        public listaEspNCientificoResponse(string listaEspNCientificoResult) {
            this.listaEspNCientificoResult = listaEspNCientificoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaEspNComun", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class listaEspNComunRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://microsoft.com/webservices/")]
        public SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser;
        
        public listaEspNComunRequest() {
        }
        
        public listaEspNComunRequest(SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser) {
            this.autenticaUser = autenticaUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaEspNComunResponse", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class listaEspNComunResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string listaEspNComunResult;
        
        public listaEspNComunResponse() {
        }
        
        public listaEspNComunResponse(string listaEspNComunResult) {
            this.listaEspNComunResult = listaEspNComunResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaDatosPOAs", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class listaDatosPOAsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://microsoft.com/webservices/")]
        public SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string codCN;
        
        public listaDatosPOAsRequest() {
        }
        
        public listaDatosPOAsRequest(SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser, string codCN) {
            this.autenticaUser = autenticaUser;
            this.codCN = codCN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaDatosPOAsResponse", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class listaDatosPOAsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string listaDatosPOAsResult;
        
        public listaDatosPOAsResponse() {
        }
        
        public listaDatosPOAsResponse(string listaDatosPOAsResult) {
            this.listaDatosPOAsResult = listaDatosPOAsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaDatosPOAs_v3", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class listaDatosPOAs_v3Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://microsoft.com/webservices/")]
        public SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string codFN;
        
        public listaDatosPOAs_v3Request() {
        }
        
        public listaDatosPOAs_v3Request(SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser, string codFN) {
            this.autenticaUser = autenticaUser;
            this.codFN = codFN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaDatosPOAs_v3Response", WrapperNamespace="http://microsoft.com/webservices/", IsWrapped=true)]
    public partial class listaDatosPOAs_v3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://microsoft.com/webservices/", Order=0)]
        public string listaDatosPOAs_v3Result;
        
        public listaDatosPOAs_v3Response() {
        }
        
        public listaDatosPOAs_v3Response(string listaDatosPOAs_v3Result) {
            this.listaDatosPOAs_v3Result = listaDatosPOAs_v3Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSSupervisionSoapChannel : SIGOFCv3.sigoWSSupervision.WSSupervisionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSSupervisionSoapClient : System.ServiceModel.ClientBase<SIGOFCv3.sigoWSSupervision.WSSupervisionSoap>, SIGOFCv3.sigoWSSupervision.WSSupervisionSoap {
        
        public WSSupervisionSoapClient() {
        }
        
        public WSSupervisionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSSupervisionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSupervisionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSupervisionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SIGOFCv3.sigoWSSupervision.listaCNotificacionesResponse SIGOFCv3.sigoWSSupervision.WSSupervisionSoap.listaCNotificaciones(SIGOFCv3.sigoWSSupervision.listaCNotificacionesRequest request) {
            return base.Channel.listaCNotificaciones(request);
        }
        
        public string listaCNotificaciones(SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser) {
            SIGOFCv3.sigoWSSupervision.listaCNotificacionesRequest inValue = new SIGOFCv3.sigoWSSupervision.listaCNotificacionesRequest();
            inValue.autenticaUser = autenticaUser;
            SIGOFCv3.sigoWSSupervision.listaCNotificacionesResponse retVal = ((SIGOFCv3.sigoWSSupervision.WSSupervisionSoap)(this)).listaCNotificaciones(inValue);
            return retVal.listaCNotificacionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.listaCNotificacionesResponse> SIGOFCv3.sigoWSSupervision.WSSupervisionSoap.listaCNotificacionesAsync(SIGOFCv3.sigoWSSupervision.listaCNotificacionesRequest request) {
            return base.Channel.listaCNotificacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.listaCNotificacionesResponse> listaCNotificacionesAsync(SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser) {
            SIGOFCv3.sigoWSSupervision.listaCNotificacionesRequest inValue = new SIGOFCv3.sigoWSSupervision.listaCNotificacionesRequest();
            inValue.autenticaUser = autenticaUser;
            return ((SIGOFCv3.sigoWSSupervision.WSSupervisionSoap)(this)).listaCNotificacionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SIGOFCv3.sigoWSSupervision.listaInformesResponse SIGOFCv3.sigoWSSupervision.WSSupervisionSoap.listaInformes(SIGOFCv3.sigoWSSupervision.listaInformesRequest request) {
            return base.Channel.listaInformes(request);
        }
        
        public string listaInformes(SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser) {
            SIGOFCv3.sigoWSSupervision.listaInformesRequest inValue = new SIGOFCv3.sigoWSSupervision.listaInformesRequest();
            inValue.autenticaUser = autenticaUser;
            SIGOFCv3.sigoWSSupervision.listaInformesResponse retVal = ((SIGOFCv3.sigoWSSupervision.WSSupervisionSoap)(this)).listaInformes(inValue);
            return retVal.listaInformesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.listaInformesResponse> SIGOFCv3.sigoWSSupervision.WSSupervisionSoap.listaInformesAsync(SIGOFCv3.sigoWSSupervision.listaInformesRequest request) {
            return base.Channel.listaInformesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.listaInformesResponse> listaInformesAsync(SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser) {
            SIGOFCv3.sigoWSSupervision.listaInformesRequest inValue = new SIGOFCv3.sigoWSSupervision.listaInformesRequest();
            inValue.autenticaUser = autenticaUser;
            return ((SIGOFCv3.sigoWSSupervision.WSSupervisionSoap)(this)).listaInformesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SIGOFCv3.sigoWSSupervision.listaMuestraResponse SIGOFCv3.sigoWSSupervision.WSSupervisionSoap.listaMuestra(SIGOFCv3.sigoWSSupervision.listaMuestraRequest request) {
            return base.Channel.listaMuestra(request);
        }
        
        public string listaMuestra(SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser, string codCN, string tipo) {
            SIGOFCv3.sigoWSSupervision.listaMuestraRequest inValue = new SIGOFCv3.sigoWSSupervision.listaMuestraRequest();
            inValue.autenticaUser = autenticaUser;
            inValue.codCN = codCN;
            inValue.tipo = tipo;
            SIGOFCv3.sigoWSSupervision.listaMuestraResponse retVal = ((SIGOFCv3.sigoWSSupervision.WSSupervisionSoap)(this)).listaMuestra(inValue);
            return retVal.listaMuestraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.listaMuestraResponse> SIGOFCv3.sigoWSSupervision.WSSupervisionSoap.listaMuestraAsync(SIGOFCv3.sigoWSSupervision.listaMuestraRequest request) {
            return base.Channel.listaMuestraAsync(request);
        }
        
        public System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.listaMuestraResponse> listaMuestraAsync(SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser, string codCN, string tipo) {
            SIGOFCv3.sigoWSSupervision.listaMuestraRequest inValue = new SIGOFCv3.sigoWSSupervision.listaMuestraRequest();
            inValue.autenticaUser = autenticaUser;
            inValue.codCN = codCN;
            inValue.tipo = tipo;
            return ((SIGOFCv3.sigoWSSupervision.WSSupervisionSoap)(this)).listaMuestraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SIGOFCv3.sigoWSSupervision.cargaDatosCampoMaderableResponse SIGOFCv3.sigoWSSupervision.WSSupervisionSoap.cargaDatosCampoMaderable(SIGOFCv3.sigoWSSupervision.cargaDatosCampoMaderableRequest request) {
            return base.Channel.cargaDatosCampoMaderable(request);
        }
        
        public string cargaDatosCampoMaderable(SIGOFCv3.sigoWSSupervision.objMaderable objMaderable, SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser) {
            SIGOFCv3.sigoWSSupervision.cargaDatosCampoMaderableRequest inValue = new SIGOFCv3.sigoWSSupervision.cargaDatosCampoMaderableRequest();
            inValue.objMaderable = objMaderable;
            inValue.autenticaUser = autenticaUser;
            SIGOFCv3.sigoWSSupervision.cargaDatosCampoMaderableResponse retVal = ((SIGOFCv3.sigoWSSupervision.WSSupervisionSoap)(this)).cargaDatosCampoMaderable(inValue);
            return retVal.cargaDatosCampoMaderableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.cargaDatosCampoMaderableResponse> SIGOFCv3.sigoWSSupervision.WSSupervisionSoap.cargaDatosCampoMaderableAsync(SIGOFCv3.sigoWSSupervision.cargaDatosCampoMaderableRequest request) {
            return base.Channel.cargaDatosCampoMaderableAsync(request);
        }
        
        public System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.cargaDatosCampoMaderableResponse> cargaDatosCampoMaderableAsync(SIGOFCv3.sigoWSSupervision.objMaderable objMaderable, SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser) {
            SIGOFCv3.sigoWSSupervision.cargaDatosCampoMaderableRequest inValue = new SIGOFCv3.sigoWSSupervision.cargaDatosCampoMaderableRequest();
            inValue.objMaderable = objMaderable;
            inValue.autenticaUser = autenticaUser;
            return ((SIGOFCv3.sigoWSSupervision.WSSupervisionSoap)(this)).cargaDatosCampoMaderableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SIGOFCv3.sigoWSSupervision.cargaDatosCampoNoMaderableResponse SIGOFCv3.sigoWSSupervision.WSSupervisionSoap.cargaDatosCampoNoMaderable(SIGOFCv3.sigoWSSupervision.cargaDatosCampoNoMaderableRequest request) {
            return base.Channel.cargaDatosCampoNoMaderable(request);
        }
        
        public string cargaDatosCampoNoMaderable(SIGOFCv3.sigoWSSupervision.objNoMaderable objNoMaderable, SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser) {
            SIGOFCv3.sigoWSSupervision.cargaDatosCampoNoMaderableRequest inValue = new SIGOFCv3.sigoWSSupervision.cargaDatosCampoNoMaderableRequest();
            inValue.objNoMaderable = objNoMaderable;
            inValue.autenticaUser = autenticaUser;
            SIGOFCv3.sigoWSSupervision.cargaDatosCampoNoMaderableResponse retVal = ((SIGOFCv3.sigoWSSupervision.WSSupervisionSoap)(this)).cargaDatosCampoNoMaderable(inValue);
            return retVal.cargaDatosCampoNoMaderableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.cargaDatosCampoNoMaderableResponse> SIGOFCv3.sigoWSSupervision.WSSupervisionSoap.cargaDatosCampoNoMaderableAsync(SIGOFCv3.sigoWSSupervision.cargaDatosCampoNoMaderableRequest request) {
            return base.Channel.cargaDatosCampoNoMaderableAsync(request);
        }
        
        public System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.cargaDatosCampoNoMaderableResponse> cargaDatosCampoNoMaderableAsync(SIGOFCv3.sigoWSSupervision.objNoMaderable objNoMaderable, SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser) {
            SIGOFCv3.sigoWSSupervision.cargaDatosCampoNoMaderableRequest inValue = new SIGOFCv3.sigoWSSupervision.cargaDatosCampoNoMaderableRequest();
            inValue.objNoMaderable = objNoMaderable;
            inValue.autenticaUser = autenticaUser;
            return ((SIGOFCv3.sigoWSSupervision.WSSupervisionSoap)(this)).cargaDatosCampoNoMaderableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SIGOFCv3.sigoWSSupervision.listaEspNCientificoResponse SIGOFCv3.sigoWSSupervision.WSSupervisionSoap.listaEspNCientifico(SIGOFCv3.sigoWSSupervision.listaEspNCientificoRequest request) {
            return base.Channel.listaEspNCientifico(request);
        }
        
        public string listaEspNCientifico(SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser) {
            SIGOFCv3.sigoWSSupervision.listaEspNCientificoRequest inValue = new SIGOFCv3.sigoWSSupervision.listaEspNCientificoRequest();
            inValue.autenticaUser = autenticaUser;
            SIGOFCv3.sigoWSSupervision.listaEspNCientificoResponse retVal = ((SIGOFCv3.sigoWSSupervision.WSSupervisionSoap)(this)).listaEspNCientifico(inValue);
            return retVal.listaEspNCientificoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.listaEspNCientificoResponse> SIGOFCv3.sigoWSSupervision.WSSupervisionSoap.listaEspNCientificoAsync(SIGOFCv3.sigoWSSupervision.listaEspNCientificoRequest request) {
            return base.Channel.listaEspNCientificoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.listaEspNCientificoResponse> listaEspNCientificoAsync(SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser) {
            SIGOFCv3.sigoWSSupervision.listaEspNCientificoRequest inValue = new SIGOFCv3.sigoWSSupervision.listaEspNCientificoRequest();
            inValue.autenticaUser = autenticaUser;
            return ((SIGOFCv3.sigoWSSupervision.WSSupervisionSoap)(this)).listaEspNCientificoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SIGOFCv3.sigoWSSupervision.listaEspNComunResponse SIGOFCv3.sigoWSSupervision.WSSupervisionSoap.listaEspNComun(SIGOFCv3.sigoWSSupervision.listaEspNComunRequest request) {
            return base.Channel.listaEspNComun(request);
        }
        
        public string listaEspNComun(SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser) {
            SIGOFCv3.sigoWSSupervision.listaEspNComunRequest inValue = new SIGOFCv3.sigoWSSupervision.listaEspNComunRequest();
            inValue.autenticaUser = autenticaUser;
            SIGOFCv3.sigoWSSupervision.listaEspNComunResponse retVal = ((SIGOFCv3.sigoWSSupervision.WSSupervisionSoap)(this)).listaEspNComun(inValue);
            return retVal.listaEspNComunResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.listaEspNComunResponse> SIGOFCv3.sigoWSSupervision.WSSupervisionSoap.listaEspNComunAsync(SIGOFCv3.sigoWSSupervision.listaEspNComunRequest request) {
            return base.Channel.listaEspNComunAsync(request);
        }
        
        public System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.listaEspNComunResponse> listaEspNComunAsync(SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser) {
            SIGOFCv3.sigoWSSupervision.listaEspNComunRequest inValue = new SIGOFCv3.sigoWSSupervision.listaEspNComunRequest();
            inValue.autenticaUser = autenticaUser;
            return ((SIGOFCv3.sigoWSSupervision.WSSupervisionSoap)(this)).listaEspNComunAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SIGOFCv3.sigoWSSupervision.listaDatosPOAsResponse SIGOFCv3.sigoWSSupervision.WSSupervisionSoap.listaDatosPOAs(SIGOFCv3.sigoWSSupervision.listaDatosPOAsRequest request) {
            return base.Channel.listaDatosPOAs(request);
        }
        
        public string listaDatosPOAs(SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser, string codCN) {
            SIGOFCv3.sigoWSSupervision.listaDatosPOAsRequest inValue = new SIGOFCv3.sigoWSSupervision.listaDatosPOAsRequest();
            inValue.autenticaUser = autenticaUser;
            inValue.codCN = codCN;
            SIGOFCv3.sigoWSSupervision.listaDatosPOAsResponse retVal = ((SIGOFCv3.sigoWSSupervision.WSSupervisionSoap)(this)).listaDatosPOAs(inValue);
            return retVal.listaDatosPOAsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.listaDatosPOAsResponse> SIGOFCv3.sigoWSSupervision.WSSupervisionSoap.listaDatosPOAsAsync(SIGOFCv3.sigoWSSupervision.listaDatosPOAsRequest request) {
            return base.Channel.listaDatosPOAsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.listaDatosPOAsResponse> listaDatosPOAsAsync(SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser, string codCN) {
            SIGOFCv3.sigoWSSupervision.listaDatosPOAsRequest inValue = new SIGOFCv3.sigoWSSupervision.listaDatosPOAsRequest();
            inValue.autenticaUser = autenticaUser;
            inValue.codCN = codCN;
            return ((SIGOFCv3.sigoWSSupervision.WSSupervisionSoap)(this)).listaDatosPOAsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SIGOFCv3.sigoWSSupervision.listaDatosPOAs_v3Response SIGOFCv3.sigoWSSupervision.WSSupervisionSoap.listaDatosPOAs_v3(SIGOFCv3.sigoWSSupervision.listaDatosPOAs_v3Request request) {
            return base.Channel.listaDatosPOAs_v3(request);
        }
        
        public string listaDatosPOAs_v3(SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser, string codFN) {
            SIGOFCv3.sigoWSSupervision.listaDatosPOAs_v3Request inValue = new SIGOFCv3.sigoWSSupervision.listaDatosPOAs_v3Request();
            inValue.autenticaUser = autenticaUser;
            inValue.codFN = codFN;
            SIGOFCv3.sigoWSSupervision.listaDatosPOAs_v3Response retVal = ((SIGOFCv3.sigoWSSupervision.WSSupervisionSoap)(this)).listaDatosPOAs_v3(inValue);
            return retVal.listaDatosPOAs_v3Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.listaDatosPOAs_v3Response> SIGOFCv3.sigoWSSupervision.WSSupervisionSoap.listaDatosPOAs_v3Async(SIGOFCv3.sigoWSSupervision.listaDatosPOAs_v3Request request) {
            return base.Channel.listaDatosPOAs_v3Async(request);
        }
        
        public System.Threading.Tasks.Task<SIGOFCv3.sigoWSSupervision.listaDatosPOAs_v3Response> listaDatosPOAs_v3Async(SIGOFCv3.sigoWSSupervision.autenticaUser autenticaUser, string codFN) {
            SIGOFCv3.sigoWSSupervision.listaDatosPOAs_v3Request inValue = new SIGOFCv3.sigoWSSupervision.listaDatosPOAs_v3Request();
            inValue.autenticaUser = autenticaUser;
            inValue.codFN = codFN;
            return ((SIGOFCv3.sigoWSSupervision.WSSupervisionSoap)(this)).listaDatosPOAs_v3Async(inValue);
        }
    }
}
