//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HistorialTH.wsObservatorio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ent_Reporte_OBSERVATORIO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HistorialTH.wsObservatorio.Ent_Reporte_OBSERVATORIO[]))]
    public partial class Ent_Reporte_OBSERVATORIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_REGISTROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TITULARField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TITULAR_BUSQUEDAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUM_THABILITANTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_MTIPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MODALIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UBICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REGIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROVINCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DISTRITOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUM_POAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PLAN_MANEJO_TOPField;
        
        private decimal VOLUMENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RES_APROBACION_POAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RES_REFORMULA_POAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VIGENCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FIN_VIGENCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZAFRAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COLORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TRAZAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string INF_FALSAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ARBOLES_INEXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CAMBIO_USOField;
        
        private decimal AREA_CAMBIO_USOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCION_ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_RESODIRECField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUM_RESOLUCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_RESOLUCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object MEDIDA_CAUTELARField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object MEDIDA_PRECAUTORIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object CADUCIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CADUCADOField;
        
        private decimal MONTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object IMPROCEDENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object FUNDADAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object FUNDADA_PARTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object INFUNDADAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object DESISTIMIENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object INADMISIBLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object NULIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object REVOCARField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object SUSPENSIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object LEVANTAR_CADUCIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object CAMBIO_MULTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DETERMINACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string INCISOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESC_ESPECIESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_REPORTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PARAMETROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHA_INICIO_THField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHA_TERMINO_THField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUM_INFORMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHA_SUPERVISION_INICIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHA_SUPERVISION_TERMINOField;
        
        private int ANIO_REFERENCIAField;
        
        private int NUM_ARBOLES_INEXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_INFORMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_ENCIENTIFICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOM_CIENTIFICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBRE_COMUNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OBSERVACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHA_INGRESOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PORCENT_BEXTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PORCENT_AUTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PORCENT_INEXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PORCENT_INJUS_VOLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VOL_INJUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_ITIPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_THABILITANTEField;
        
        private int NUM_POA_INTField;
        
        private decimal VOLUMEN_BEXTField;
        
        private decimal VOLUMEN_AUTField;
        
        private decimal VOLUMEN_DECLARADOField;
        
        private decimal VOLUMEN_VERIFICADOField;
        
        private int NUM_ARB_MUESTRAField;
        
        private int NUM_ARB_INEXField;
        
        private int NUM_ARB_EXISTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHA_BEXTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string INFRACCIONESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TEXTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object RD_MOSTRAR_INCISOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TEXTO_CADUCAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URL_RESOLUCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CONSULTORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REGENTE_IMPLEMENTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ES_ALERTA_OSINFORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_SUPERVISIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_MEDIDAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUM_RESOLUCION_DERICTORALField;
        
        private decimal PERDIDA_COBERTURAField;
        
        private decimal APROV_NO_AUTORIZADOField;
        
        private int SIGNIFICANCIAField;
        
        private int IRREPARABILIDADField;
        
        private int VALOR_IMPACTOField;
        
        private int VALOR_PROBABILIDAD_1Field;
        
        private int VALOR_PROBABILIDAD_2Field;
        
        private int VALOR_PROBABILIDAD_3Field;
        
        private int RESULTADOField;
        
        private int CANT_ESP_VOL_INJUSField;
        
        private int CANT_ESP_SUPERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HistorialTH.wsObservatorio.Ent_Reporte_OBSERVATORIO[] List_Resumen_ROJOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HistorialTH.wsObservatorio.Ent_Reporte_OBSERVATORIO[] List_Resumen_AMBARField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HistorialTH.wsObservatorio.Ent_Reporte_OBSERVATORIO[] List_Resumen_VERDEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HistorialTH.wsObservatorio.Ent_Reporte_OBSERVATORIO[] List_ResolucionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HistorialTH.wsObservatorio.Ent_Reporte_OBSERVATORIO[] List_Detalle_TitularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusValorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADO_THField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUM_RDINICIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUM_RDTERMINOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ARCH_EVI_IRREGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object NUMERO_RESOLUCION_ALERTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALERTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object FECHA_ENVIO_ALERTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUM_RESOLUCION_ANT_PAUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUMERO_ALERTAField;
        
        private decimal VOLUMEN_ALERTAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_REGISTRO {
            get {
                return this.ID_REGISTROField;
            }
            set {
                if ((this.ID_REGISTROField.Equals(value) != true)) {
                    this.ID_REGISTROField = value;
                    this.RaisePropertyChanged("ID_REGISTRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TITULAR {
            get {
                return this.TITULARField;
            }
            set {
                if ((object.ReferenceEquals(this.TITULARField, value) != true)) {
                    this.TITULARField = value;
                    this.RaisePropertyChanged("TITULAR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TITULAR_BUSQUEDA {
            get {
                return this.TITULAR_BUSQUEDAField;
            }
            set {
                if ((object.ReferenceEquals(this.TITULAR_BUSQUEDAField, value) != true)) {
                    this.TITULAR_BUSQUEDAField = value;
                    this.RaisePropertyChanged("TITULAR_BUSQUEDA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NUM_THABILITANTE {
            get {
                return this.NUM_THABILITANTEField;
            }
            set {
                if ((object.ReferenceEquals(this.NUM_THABILITANTEField, value) != true)) {
                    this.NUM_THABILITANTEField = value;
                    this.RaisePropertyChanged("NUM_THABILITANTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string RUC {
            get {
                return this.RUCField;
            }
            set {
                if ((object.ReferenceEquals(this.RUCField, value) != true)) {
                    this.RUCField = value;
                    this.RaisePropertyChanged("RUC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string COD_MTIPO {
            get {
                return this.COD_MTIPOField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_MTIPOField, value) != true)) {
                    this.COD_MTIPOField = value;
                    this.RaisePropertyChanged("COD_MTIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MODALIDAD {
            get {
                return this.MODALIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.MODALIDADField, value) != true)) {
                    this.MODALIDADField = value;
                    this.RaisePropertyChanged("MODALIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string UBICACION {
            get {
                return this.UBICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.UBICACIONField, value) != true)) {
                    this.UBICACIONField = value;
                    this.RaisePropertyChanged("UBICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string REGION {
            get {
                return this.REGIONField;
            }
            set {
                if ((object.ReferenceEquals(this.REGIONField, value) != true)) {
                    this.REGIONField = value;
                    this.RaisePropertyChanged("REGION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string PROVINCIA {
            get {
                return this.PROVINCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.PROVINCIAField, value) != true)) {
                    this.PROVINCIAField = value;
                    this.RaisePropertyChanged("PROVINCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string DISTRITO {
            get {
                return this.DISTRITOField;
            }
            set {
                if ((object.ReferenceEquals(this.DISTRITOField, value) != true)) {
                    this.DISTRITOField = value;
                    this.RaisePropertyChanged("DISTRITO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string NUM_POA {
            get {
                return this.NUM_POAField;
            }
            set {
                if ((object.ReferenceEquals(this.NUM_POAField, value) != true)) {
                    this.NUM_POAField = value;
                    this.RaisePropertyChanged("NUM_POA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string PLAN_MANEJO_TOP {
            get {
                return this.PLAN_MANEJO_TOPField;
            }
            set {
                if ((object.ReferenceEquals(this.PLAN_MANEJO_TOPField, value) != true)) {
                    this.PLAN_MANEJO_TOPField = value;
                    this.RaisePropertyChanged("PLAN_MANEJO_TOP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public decimal VOLUMEN {
            get {
                return this.VOLUMENField;
            }
            set {
                if ((this.VOLUMENField.Equals(value) != true)) {
                    this.VOLUMENField = value;
                    this.RaisePropertyChanged("VOLUMEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string RES_APROBACION_POA {
            get {
                return this.RES_APROBACION_POAField;
            }
            set {
                if ((object.ReferenceEquals(this.RES_APROBACION_POAField, value) != true)) {
                    this.RES_APROBACION_POAField = value;
                    this.RaisePropertyChanged("RES_APROBACION_POA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string RES_REFORMULA_POA {
            get {
                return this.RES_REFORMULA_POAField;
            }
            set {
                if ((object.ReferenceEquals(this.RES_REFORMULA_POAField, value) != true)) {
                    this.RES_REFORMULA_POAField = value;
                    this.RaisePropertyChanged("RES_REFORMULA_POA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string VIGENCIA {
            get {
                return this.VIGENCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.VIGENCIAField, value) != true)) {
                    this.VIGENCIAField = value;
                    this.RaisePropertyChanged("VIGENCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string FIN_VIGENCIA {
            get {
                return this.FIN_VIGENCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.FIN_VIGENCIAField, value) != true)) {
                    this.FIN_VIGENCIAField = value;
                    this.RaisePropertyChanged("FIN_VIGENCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string ZAFRA {
            get {
                return this.ZAFRAField;
            }
            set {
                if ((object.ReferenceEquals(this.ZAFRAField, value) != true)) {
                    this.ZAFRAField = value;
                    this.RaisePropertyChanged("ZAFRA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string COLOR {
            get {
                return this.COLORField;
            }
            set {
                if ((object.ReferenceEquals(this.COLORField, value) != true)) {
                    this.COLORField = value;
                    this.RaisePropertyChanged("COLOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string TRAZA {
            get {
                return this.TRAZAField;
            }
            set {
                if ((object.ReferenceEquals(this.TRAZAField, value) != true)) {
                    this.TRAZAField = value;
                    this.RaisePropertyChanged("TRAZA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string INF_FALSA {
            get {
                return this.INF_FALSAField;
            }
            set {
                if ((object.ReferenceEquals(this.INF_FALSAField, value) != true)) {
                    this.INF_FALSAField = value;
                    this.RaisePropertyChanged("INF_FALSA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string ARBOLES_INEX {
            get {
                return this.ARBOLES_INEXField;
            }
            set {
                if ((object.ReferenceEquals(this.ARBOLES_INEXField, value) != true)) {
                    this.ARBOLES_INEXField = value;
                    this.RaisePropertyChanged("ARBOLES_INEX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string CAMBIO_USO {
            get {
                return this.CAMBIO_USOField;
            }
            set {
                if ((object.ReferenceEquals(this.CAMBIO_USOField, value) != true)) {
                    this.CAMBIO_USOField = value;
                    this.RaisePropertyChanged("CAMBIO_USO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public decimal AREA_CAMBIO_USO {
            get {
                return this.AREA_CAMBIO_USOField;
            }
            set {
                if ((this.AREA_CAMBIO_USOField.Equals(value) != true)) {
                    this.AREA_CAMBIO_USOField = value;
                    this.RaisePropertyChanged("AREA_CAMBIO_USO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADOField, value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string DESCRIPCION_ESTADO {
            get {
                return this.DESCRIPCION_ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCION_ESTADOField, value) != true)) {
                    this.DESCRIPCION_ESTADOField = value;
                    this.RaisePropertyChanged("DESCRIPCION_ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string COD_RESODIREC {
            get {
                return this.COD_RESODIRECField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_RESODIRECField, value) != true)) {
                    this.COD_RESODIRECField = value;
                    this.RaisePropertyChanged("COD_RESODIREC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string NUM_RESOLUCION {
            get {
                return this.NUM_RESOLUCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.NUM_RESOLUCIONField, value) != true)) {
                    this.NUM_RESOLUCIONField = value;
                    this.RaisePropertyChanged("NUM_RESOLUCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string TIPO_RESOLUCION {
            get {
                return this.TIPO_RESOLUCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_RESOLUCIONField, value) != true)) {
                    this.TIPO_RESOLUCIONField = value;
                    this.RaisePropertyChanged("TIPO_RESOLUCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public object MEDIDA_CAUTELAR {
            get {
                return this.MEDIDA_CAUTELARField;
            }
            set {
                if ((object.ReferenceEquals(this.MEDIDA_CAUTELARField, value) != true)) {
                    this.MEDIDA_CAUTELARField = value;
                    this.RaisePropertyChanged("MEDIDA_CAUTELAR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public object MEDIDA_PRECAUTORIA {
            get {
                return this.MEDIDA_PRECAUTORIAField;
            }
            set {
                if ((object.ReferenceEquals(this.MEDIDA_PRECAUTORIAField, value) != true)) {
                    this.MEDIDA_PRECAUTORIAField = value;
                    this.RaisePropertyChanged("MEDIDA_PRECAUTORIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public object CADUCIDAD {
            get {
                return this.CADUCIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.CADUCIDADField, value) != true)) {
                    this.CADUCIDADField = value;
                    this.RaisePropertyChanged("CADUCIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string CADUCADO {
            get {
                return this.CADUCADOField;
            }
            set {
                if ((object.ReferenceEquals(this.CADUCADOField, value) != true)) {
                    this.CADUCADOField = value;
                    this.RaisePropertyChanged("CADUCADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=34)]
        public decimal MONTO {
            get {
                return this.MONTOField;
            }
            set {
                if ((this.MONTOField.Equals(value) != true)) {
                    this.MONTOField = value;
                    this.RaisePropertyChanged("MONTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public object IMPROCEDENTE {
            get {
                return this.IMPROCEDENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.IMPROCEDENTEField, value) != true)) {
                    this.IMPROCEDENTEField = value;
                    this.RaisePropertyChanged("IMPROCEDENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public object FUNDADA {
            get {
                return this.FUNDADAField;
            }
            set {
                if ((object.ReferenceEquals(this.FUNDADAField, value) != true)) {
                    this.FUNDADAField = value;
                    this.RaisePropertyChanged("FUNDADA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public object FUNDADA_PARTE {
            get {
                return this.FUNDADA_PARTEField;
            }
            set {
                if ((object.ReferenceEquals(this.FUNDADA_PARTEField, value) != true)) {
                    this.FUNDADA_PARTEField = value;
                    this.RaisePropertyChanged("FUNDADA_PARTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=38)]
        public object INFUNDADA {
            get {
                return this.INFUNDADAField;
            }
            set {
                if ((object.ReferenceEquals(this.INFUNDADAField, value) != true)) {
                    this.INFUNDADAField = value;
                    this.RaisePropertyChanged("INFUNDADA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public object DESISTIMIENTO {
            get {
                return this.DESISTIMIENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.DESISTIMIENTOField, value) != true)) {
                    this.DESISTIMIENTOField = value;
                    this.RaisePropertyChanged("DESISTIMIENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public object INADMISIBLE {
            get {
                return this.INADMISIBLEField;
            }
            set {
                if ((object.ReferenceEquals(this.INADMISIBLEField, value) != true)) {
                    this.INADMISIBLEField = value;
                    this.RaisePropertyChanged("INADMISIBLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=41)]
        public object NULIDAD {
            get {
                return this.NULIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.NULIDADField, value) != true)) {
                    this.NULIDADField = value;
                    this.RaisePropertyChanged("NULIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public object REVOCAR {
            get {
                return this.REVOCARField;
            }
            set {
                if ((object.ReferenceEquals(this.REVOCARField, value) != true)) {
                    this.REVOCARField = value;
                    this.RaisePropertyChanged("REVOCAR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public object SUSPENSION {
            get {
                return this.SUSPENSIONField;
            }
            set {
                if ((object.ReferenceEquals(this.SUSPENSIONField, value) != true)) {
                    this.SUSPENSIONField = value;
                    this.RaisePropertyChanged("SUSPENSION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=44)]
        public object LEVANTAR_CADUCIDAD {
            get {
                return this.LEVANTAR_CADUCIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.LEVANTAR_CADUCIDADField, value) != true)) {
                    this.LEVANTAR_CADUCIDADField = value;
                    this.RaisePropertyChanged("LEVANTAR_CADUCIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public object CAMBIO_MULTA {
            get {
                return this.CAMBIO_MULTAField;
            }
            set {
                if ((object.ReferenceEquals(this.CAMBIO_MULTAField, value) != true)) {
                    this.CAMBIO_MULTAField = value;
                    this.RaisePropertyChanged("CAMBIO_MULTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=46)]
        public string DETERMINACION {
            get {
                return this.DETERMINACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DETERMINACIONField, value) != true)) {
                    this.DETERMINACIONField = value;
                    this.RaisePropertyChanged("DETERMINACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=47)]
        public string INCISO {
            get {
                return this.INCISOField;
            }
            set {
                if ((object.ReferenceEquals(this.INCISOField, value) != true)) {
                    this.INCISOField = value;
                    this.RaisePropertyChanged("INCISO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=48)]
        public string DESC_ESPECIES {
            get {
                return this.DESC_ESPECIESField;
            }
            set {
                if ((object.ReferenceEquals(this.DESC_ESPECIESField, value) != true)) {
                    this.DESC_ESPECIESField = value;
                    this.RaisePropertyChanged("DESC_ESPECIES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=49)]
        public string TIPO_REPORTE {
            get {
                return this.TIPO_REPORTEField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_REPORTEField, value) != true)) {
                    this.TIPO_REPORTEField = value;
                    this.RaisePropertyChanged("TIPO_REPORTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=50)]
        public string PARAMETRO {
            get {
                return this.PARAMETROField;
            }
            set {
                if ((object.ReferenceEquals(this.PARAMETROField, value) != true)) {
                    this.PARAMETROField = value;
                    this.RaisePropertyChanged("PARAMETRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=51)]
        public string FECHA {
            get {
                return this.FECHAField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHAField, value) != true)) {
                    this.FECHAField = value;
                    this.RaisePropertyChanged("FECHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=52)]
        public string FECHA_INICIO_TH {
            get {
                return this.FECHA_INICIO_THField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHA_INICIO_THField, value) != true)) {
                    this.FECHA_INICIO_THField = value;
                    this.RaisePropertyChanged("FECHA_INICIO_TH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=53)]
        public string FECHA_TERMINO_TH {
            get {
                return this.FECHA_TERMINO_THField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHA_TERMINO_THField, value) != true)) {
                    this.FECHA_TERMINO_THField = value;
                    this.RaisePropertyChanged("FECHA_TERMINO_TH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=54)]
        public string NUM_INFORME {
            get {
                return this.NUM_INFORMEField;
            }
            set {
                if ((object.ReferenceEquals(this.NUM_INFORMEField, value) != true)) {
                    this.NUM_INFORMEField = value;
                    this.RaisePropertyChanged("NUM_INFORME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=55)]
        public string FECHA_SUPERVISION_INICIO {
            get {
                return this.FECHA_SUPERVISION_INICIOField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHA_SUPERVISION_INICIOField, value) != true)) {
                    this.FECHA_SUPERVISION_INICIOField = value;
                    this.RaisePropertyChanged("FECHA_SUPERVISION_INICIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=56)]
        public string FECHA_SUPERVISION_TERMINO {
            get {
                return this.FECHA_SUPERVISION_TERMINOField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHA_SUPERVISION_TERMINOField, value) != true)) {
                    this.FECHA_SUPERVISION_TERMINOField = value;
                    this.RaisePropertyChanged("FECHA_SUPERVISION_TERMINO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=57)]
        public int ANIO_REFERENCIA {
            get {
                return this.ANIO_REFERENCIAField;
            }
            set {
                if ((this.ANIO_REFERENCIAField.Equals(value) != true)) {
                    this.ANIO_REFERENCIAField = value;
                    this.RaisePropertyChanged("ANIO_REFERENCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=58)]
        public int NUM_ARBOLES_INEX {
            get {
                return this.NUM_ARBOLES_INEXField;
            }
            set {
                if ((this.NUM_ARBOLES_INEXField.Equals(value) != true)) {
                    this.NUM_ARBOLES_INEXField = value;
                    this.RaisePropertyChanged("NUM_ARBOLES_INEX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=59)]
        public string COD_INFORME {
            get {
                return this.COD_INFORMEField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_INFORMEField, value) != true)) {
                    this.COD_INFORMEField = value;
                    this.RaisePropertyChanged("COD_INFORME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=60)]
        public string COD_ENCIENTIFICO {
            get {
                return this.COD_ENCIENTIFICOField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_ENCIENTIFICOField, value) != true)) {
                    this.COD_ENCIENTIFICOField = value;
                    this.RaisePropertyChanged("COD_ENCIENTIFICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=61)]
        public string NOM_CIENTIFICO {
            get {
                return this.NOM_CIENTIFICOField;
            }
            set {
                if ((object.ReferenceEquals(this.NOM_CIENTIFICOField, value) != true)) {
                    this.NOM_CIENTIFICOField = value;
                    this.RaisePropertyChanged("NOM_CIENTIFICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=62)]
        public string NOMBRE_COMUN {
            get {
                return this.NOMBRE_COMUNField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBRE_COMUNField, value) != true)) {
                    this.NOMBRE_COMUNField = value;
                    this.RaisePropertyChanged("NOMBRE_COMUN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=63)]
        public string OBSERVACION {
            get {
                return this.OBSERVACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.OBSERVACIONField, value) != true)) {
                    this.OBSERVACIONField = value;
                    this.RaisePropertyChanged("OBSERVACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=64)]
        public string FECHA_INGRESO {
            get {
                return this.FECHA_INGRESOField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHA_INGRESOField, value) != true)) {
                    this.FECHA_INGRESOField = value;
                    this.RaisePropertyChanged("FECHA_INGRESO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=65)]
        public string PORCENT_BEXT {
            get {
                return this.PORCENT_BEXTField;
            }
            set {
                if ((object.ReferenceEquals(this.PORCENT_BEXTField, value) != true)) {
                    this.PORCENT_BEXTField = value;
                    this.RaisePropertyChanged("PORCENT_BEXT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=66)]
        public string PORCENT_AUT {
            get {
                return this.PORCENT_AUTField;
            }
            set {
                if ((object.ReferenceEquals(this.PORCENT_AUTField, value) != true)) {
                    this.PORCENT_AUTField = value;
                    this.RaisePropertyChanged("PORCENT_AUT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=67)]
        public string PORCENT_INEX {
            get {
                return this.PORCENT_INEXField;
            }
            set {
                if ((object.ReferenceEquals(this.PORCENT_INEXField, value) != true)) {
                    this.PORCENT_INEXField = value;
                    this.RaisePropertyChanged("PORCENT_INEX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=68)]
        public string PORCENT_INJUS_VOL {
            get {
                return this.PORCENT_INJUS_VOLField;
            }
            set {
                if ((object.ReferenceEquals(this.PORCENT_INJUS_VOLField, value) != true)) {
                    this.PORCENT_INJUS_VOLField = value;
                    this.RaisePropertyChanged("PORCENT_INJUS_VOL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=69)]
        public string VOL_INJUS {
            get {
                return this.VOL_INJUSField;
            }
            set {
                if ((object.ReferenceEquals(this.VOL_INJUSField, value) != true)) {
                    this.VOL_INJUSField = value;
                    this.RaisePropertyChanged("VOL_INJUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=70)]
        public string COD_ITIPO {
            get {
                return this.COD_ITIPOField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_ITIPOField, value) != true)) {
                    this.COD_ITIPOField = value;
                    this.RaisePropertyChanged("COD_ITIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=71)]
        public string COD_THABILITANTE {
            get {
                return this.COD_THABILITANTEField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_THABILITANTEField, value) != true)) {
                    this.COD_THABILITANTEField = value;
                    this.RaisePropertyChanged("COD_THABILITANTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=72)]
        public int NUM_POA_INT {
            get {
                return this.NUM_POA_INTField;
            }
            set {
                if ((this.NUM_POA_INTField.Equals(value) != true)) {
                    this.NUM_POA_INTField = value;
                    this.RaisePropertyChanged("NUM_POA_INT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=73)]
        public decimal VOLUMEN_BEXT {
            get {
                return this.VOLUMEN_BEXTField;
            }
            set {
                if ((this.VOLUMEN_BEXTField.Equals(value) != true)) {
                    this.VOLUMEN_BEXTField = value;
                    this.RaisePropertyChanged("VOLUMEN_BEXT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=74)]
        public decimal VOLUMEN_AUT {
            get {
                return this.VOLUMEN_AUTField;
            }
            set {
                if ((this.VOLUMEN_AUTField.Equals(value) != true)) {
                    this.VOLUMEN_AUTField = value;
                    this.RaisePropertyChanged("VOLUMEN_AUT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=75)]
        public decimal VOLUMEN_DECLARADO {
            get {
                return this.VOLUMEN_DECLARADOField;
            }
            set {
                if ((this.VOLUMEN_DECLARADOField.Equals(value) != true)) {
                    this.VOLUMEN_DECLARADOField = value;
                    this.RaisePropertyChanged("VOLUMEN_DECLARADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=76)]
        public decimal VOLUMEN_VERIFICADO {
            get {
                return this.VOLUMEN_VERIFICADOField;
            }
            set {
                if ((this.VOLUMEN_VERIFICADOField.Equals(value) != true)) {
                    this.VOLUMEN_VERIFICADOField = value;
                    this.RaisePropertyChanged("VOLUMEN_VERIFICADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=77)]
        public int NUM_ARB_MUESTRA {
            get {
                return this.NUM_ARB_MUESTRAField;
            }
            set {
                if ((this.NUM_ARB_MUESTRAField.Equals(value) != true)) {
                    this.NUM_ARB_MUESTRAField = value;
                    this.RaisePropertyChanged("NUM_ARB_MUESTRA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=78)]
        public int NUM_ARB_INEX {
            get {
                return this.NUM_ARB_INEXField;
            }
            set {
                if ((this.NUM_ARB_INEXField.Equals(value) != true)) {
                    this.NUM_ARB_INEXField = value;
                    this.RaisePropertyChanged("NUM_ARB_INEX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=79)]
        public int NUM_ARB_EXIST {
            get {
                return this.NUM_ARB_EXISTField;
            }
            set {
                if ((this.NUM_ARB_EXISTField.Equals(value) != true)) {
                    this.NUM_ARB_EXISTField = value;
                    this.RaisePropertyChanged("NUM_ARB_EXIST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=80)]
        public string FECHA_BEXT {
            get {
                return this.FECHA_BEXTField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHA_BEXTField, value) != true)) {
                    this.FECHA_BEXTField = value;
                    this.RaisePropertyChanged("FECHA_BEXT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=81)]
        public string INFRACCIONES {
            get {
                return this.INFRACCIONESField;
            }
            set {
                if ((object.ReferenceEquals(this.INFRACCIONESField, value) != true)) {
                    this.INFRACCIONESField = value;
                    this.RaisePropertyChanged("INFRACCIONES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=82)]
        public string TEXTO {
            get {
                return this.TEXTOField;
            }
            set {
                if ((object.ReferenceEquals(this.TEXTOField, value) != true)) {
                    this.TEXTOField = value;
                    this.RaisePropertyChanged("TEXTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=83)]
        public object RD_MOSTRAR_INCISOS {
            get {
                return this.RD_MOSTRAR_INCISOSField;
            }
            set {
                if ((object.ReferenceEquals(this.RD_MOSTRAR_INCISOSField, value) != true)) {
                    this.RD_MOSTRAR_INCISOSField = value;
                    this.RaisePropertyChanged("RD_MOSTRAR_INCISOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=84)]
        public string TEXTO_CADUCA {
            get {
                return this.TEXTO_CADUCAField;
            }
            set {
                if ((object.ReferenceEquals(this.TEXTO_CADUCAField, value) != true)) {
                    this.TEXTO_CADUCAField = value;
                    this.RaisePropertyChanged("TEXTO_CADUCA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=85)]
        public string URL_RESOLUCION {
            get {
                return this.URL_RESOLUCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.URL_RESOLUCIONField, value) != true)) {
                    this.URL_RESOLUCIONField = value;
                    this.RaisePropertyChanged("URL_RESOLUCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=86)]
        public string CONSULTOR {
            get {
                return this.CONSULTORField;
            }
            set {
                if ((object.ReferenceEquals(this.CONSULTORField, value) != true)) {
                    this.CONSULTORField = value;
                    this.RaisePropertyChanged("CONSULTOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=87)]
        public string REGENTE_IMPLEMENTA {
            get {
                return this.REGENTE_IMPLEMENTAField;
            }
            set {
                if ((object.ReferenceEquals(this.REGENTE_IMPLEMENTAField, value) != true)) {
                    this.REGENTE_IMPLEMENTAField = value;
                    this.RaisePropertyChanged("REGENTE_IMPLEMENTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=88)]
        public string ES_ALERTA_OSINFOR {
            get {
                return this.ES_ALERTA_OSINFORField;
            }
            set {
                if ((object.ReferenceEquals(this.ES_ALERTA_OSINFORField, value) != true)) {
                    this.ES_ALERTA_OSINFORField = value;
                    this.RaisePropertyChanged("ES_ALERTA_OSINFOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=89)]
        public string TIPO_SUPERVISION {
            get {
                return this.TIPO_SUPERVISIONField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_SUPERVISIONField, value) != true)) {
                    this.TIPO_SUPERVISIONField = value;
                    this.RaisePropertyChanged("TIPO_SUPERVISION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=90)]
        public string TIPO_MEDIDA {
            get {
                return this.TIPO_MEDIDAField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_MEDIDAField, value) != true)) {
                    this.TIPO_MEDIDAField = value;
                    this.RaisePropertyChanged("TIPO_MEDIDA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=91)]
        public string NUM_RESOLUCION_DERICTORAL {
            get {
                return this.NUM_RESOLUCION_DERICTORALField;
            }
            set {
                if ((object.ReferenceEquals(this.NUM_RESOLUCION_DERICTORALField, value) != true)) {
                    this.NUM_RESOLUCION_DERICTORALField = value;
                    this.RaisePropertyChanged("NUM_RESOLUCION_DERICTORAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=92)]
        public decimal PERDIDA_COBERTURA {
            get {
                return this.PERDIDA_COBERTURAField;
            }
            set {
                if ((this.PERDIDA_COBERTURAField.Equals(value) != true)) {
                    this.PERDIDA_COBERTURAField = value;
                    this.RaisePropertyChanged("PERDIDA_COBERTURA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=93)]
        public decimal APROV_NO_AUTORIZADO {
            get {
                return this.APROV_NO_AUTORIZADOField;
            }
            set {
                if ((this.APROV_NO_AUTORIZADOField.Equals(value) != true)) {
                    this.APROV_NO_AUTORIZADOField = value;
                    this.RaisePropertyChanged("APROV_NO_AUTORIZADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=94)]
        public int SIGNIFICANCIA {
            get {
                return this.SIGNIFICANCIAField;
            }
            set {
                if ((this.SIGNIFICANCIAField.Equals(value) != true)) {
                    this.SIGNIFICANCIAField = value;
                    this.RaisePropertyChanged("SIGNIFICANCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=95)]
        public int IRREPARABILIDAD {
            get {
                return this.IRREPARABILIDADField;
            }
            set {
                if ((this.IRREPARABILIDADField.Equals(value) != true)) {
                    this.IRREPARABILIDADField = value;
                    this.RaisePropertyChanged("IRREPARABILIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=96)]
        public int VALOR_IMPACTO {
            get {
                return this.VALOR_IMPACTOField;
            }
            set {
                if ((this.VALOR_IMPACTOField.Equals(value) != true)) {
                    this.VALOR_IMPACTOField = value;
                    this.RaisePropertyChanged("VALOR_IMPACTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=97)]
        public int VALOR_PROBABILIDAD_1 {
            get {
                return this.VALOR_PROBABILIDAD_1Field;
            }
            set {
                if ((this.VALOR_PROBABILIDAD_1Field.Equals(value) != true)) {
                    this.VALOR_PROBABILIDAD_1Field = value;
                    this.RaisePropertyChanged("VALOR_PROBABILIDAD_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=98)]
        public int VALOR_PROBABILIDAD_2 {
            get {
                return this.VALOR_PROBABILIDAD_2Field;
            }
            set {
                if ((this.VALOR_PROBABILIDAD_2Field.Equals(value) != true)) {
                    this.VALOR_PROBABILIDAD_2Field = value;
                    this.RaisePropertyChanged("VALOR_PROBABILIDAD_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=99)]
        public int VALOR_PROBABILIDAD_3 {
            get {
                return this.VALOR_PROBABILIDAD_3Field;
            }
            set {
                if ((this.VALOR_PROBABILIDAD_3Field.Equals(value) != true)) {
                    this.VALOR_PROBABILIDAD_3Field = value;
                    this.RaisePropertyChanged("VALOR_PROBABILIDAD_3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=100)]
        public int RESULTADO {
            get {
                return this.RESULTADOField;
            }
            set {
                if ((this.RESULTADOField.Equals(value) != true)) {
                    this.RESULTADOField = value;
                    this.RaisePropertyChanged("RESULTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=101)]
        public int CANT_ESP_VOL_INJUS {
            get {
                return this.CANT_ESP_VOL_INJUSField;
            }
            set {
                if ((this.CANT_ESP_VOL_INJUSField.Equals(value) != true)) {
                    this.CANT_ESP_VOL_INJUSField = value;
                    this.RaisePropertyChanged("CANT_ESP_VOL_INJUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=102)]
        public int CANT_ESP_SUPER {
            get {
                return this.CANT_ESP_SUPERField;
            }
            set {
                if ((this.CANT_ESP_SUPERField.Equals(value) != true)) {
                    this.CANT_ESP_SUPERField = value;
                    this.RaisePropertyChanged("CANT_ESP_SUPER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=103)]
        public HistorialTH.wsObservatorio.Ent_Reporte_OBSERVATORIO[] List_Resumen_ROJO {
            get {
                return this.List_Resumen_ROJOField;
            }
            set {
                if ((object.ReferenceEquals(this.List_Resumen_ROJOField, value) != true)) {
                    this.List_Resumen_ROJOField = value;
                    this.RaisePropertyChanged("List_Resumen_ROJO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=104)]
        public HistorialTH.wsObservatorio.Ent_Reporte_OBSERVATORIO[] List_Resumen_AMBAR {
            get {
                return this.List_Resumen_AMBARField;
            }
            set {
                if ((object.ReferenceEquals(this.List_Resumen_AMBARField, value) != true)) {
                    this.List_Resumen_AMBARField = value;
                    this.RaisePropertyChanged("List_Resumen_AMBAR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=105)]
        public HistorialTH.wsObservatorio.Ent_Reporte_OBSERVATORIO[] List_Resumen_VERDE {
            get {
                return this.List_Resumen_VERDEField;
            }
            set {
                if ((object.ReferenceEquals(this.List_Resumen_VERDEField, value) != true)) {
                    this.List_Resumen_VERDEField = value;
                    this.RaisePropertyChanged("List_Resumen_VERDE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=106)]
        public HistorialTH.wsObservatorio.Ent_Reporte_OBSERVATORIO[] List_Resoluciones {
            get {
                return this.List_ResolucionesField;
            }
            set {
                if ((object.ReferenceEquals(this.List_ResolucionesField, value) != true)) {
                    this.List_ResolucionesField = value;
                    this.RaisePropertyChanged("List_Resoluciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=107)]
        public HistorialTH.wsObservatorio.Ent_Reporte_OBSERVATORIO[] List_Detalle_Titular {
            get {
                return this.List_Detalle_TitularField;
            }
            set {
                if ((object.ReferenceEquals(this.List_Detalle_TitularField, value) != true)) {
                    this.List_Detalle_TitularField = value;
                    this.RaisePropertyChanged("List_Detalle_Titular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=108)]
        public string BusValor {
            get {
                return this.BusValorField;
            }
            set {
                if ((object.ReferenceEquals(this.BusValorField, value) != true)) {
                    this.BusValorField = value;
                    this.RaisePropertyChanged("BusValor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=109)]
        public string ESTADO_TH {
            get {
                return this.ESTADO_THField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADO_THField, value) != true)) {
                    this.ESTADO_THField = value;
                    this.RaisePropertyChanged("ESTADO_TH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=110)]
        public string NUM_RDINICIO {
            get {
                return this.NUM_RDINICIOField;
            }
            set {
                if ((object.ReferenceEquals(this.NUM_RDINICIOField, value) != true)) {
                    this.NUM_RDINICIOField = value;
                    this.RaisePropertyChanged("NUM_RDINICIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=111)]
        public string NUM_RDTERMINO {
            get {
                return this.NUM_RDTERMINOField;
            }
            set {
                if ((object.ReferenceEquals(this.NUM_RDTERMINOField, value) != true)) {
                    this.NUM_RDTERMINOField = value;
                    this.RaisePropertyChanged("NUM_RDTERMINO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=112)]
        public object ARCH_EVI_IRREG {
            get {
                return this.ARCH_EVI_IRREGField;
            }
            set {
                if ((object.ReferenceEquals(this.ARCH_EVI_IRREGField, value) != true)) {
                    this.ARCH_EVI_IRREGField = value;
                    this.RaisePropertyChanged("ARCH_EVI_IRREG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=113)]
        public object NUMERO_RESOLUCION_ALERTA {
            get {
                return this.NUMERO_RESOLUCION_ALERTAField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_RESOLUCION_ALERTAField, value) != true)) {
                    this.NUMERO_RESOLUCION_ALERTAField = value;
                    this.RaisePropertyChanged("NUMERO_RESOLUCION_ALERTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=114)]
        public string ALERTA {
            get {
                return this.ALERTAField;
            }
            set {
                if ((object.ReferenceEquals(this.ALERTAField, value) != true)) {
                    this.ALERTAField = value;
                    this.RaisePropertyChanged("ALERTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=115)]
        public object FECHA_ENVIO_ALERTA {
            get {
                return this.FECHA_ENVIO_ALERTAField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHA_ENVIO_ALERTAField, value) != true)) {
                    this.FECHA_ENVIO_ALERTAField = value;
                    this.RaisePropertyChanged("FECHA_ENVIO_ALERTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=116)]
        public string NUM_RESOLUCION_ANT_PAU {
            get {
                return this.NUM_RESOLUCION_ANT_PAUField;
            }
            set {
                if ((object.ReferenceEquals(this.NUM_RESOLUCION_ANT_PAUField, value) != true)) {
                    this.NUM_RESOLUCION_ANT_PAUField = value;
                    this.RaisePropertyChanged("NUM_RESOLUCION_ANT_PAU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=117)]
        public string NUMERO_ALERTA {
            get {
                return this.NUMERO_ALERTAField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMERO_ALERTAField, value) != true)) {
                    this.NUMERO_ALERTAField = value;
                    this.RaisePropertyChanged("NUMERO_ALERTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=118)]
        public decimal VOLUMEN_ALERTA {
            get {
                return this.VOLUMEN_ALERTAField;
            }
            set {
                if ((this.VOLUMEN_ALERTAField.Equals(value) != true)) {
                    this.VOLUMEN_ALERTAField = value;
                    this.RaisePropertyChanged("VOLUMEN_ALERTA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsObservatorio.WSObservatorioSoap")]
    public interface WSObservatorioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento mapPath del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/escribirDetallePDFIndex", ReplyAction="*")]
        HistorialTH.wsObservatorio.escribirDetallePDFIndexResponse escribirDetallePDFIndex(HistorialTH.wsObservatorio.escribirDetallePDFIndexRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/escribirDetallePDFIndex", ReplyAction="*")]
        System.Threading.Tasks.Task<HistorialTH.wsObservatorio.escribirDetallePDFIndexResponse> escribirDetallePDFIndexAsync(HistorialTH.wsObservatorio.escribirDetallePDFIndexRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento elementListado del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/escribirDetallePDF", ReplyAction="*")]
        HistorialTH.wsObservatorio.escribirDetallePDFResponse escribirDetallePDF(HistorialTH.wsObservatorio.escribirDetallePDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/escribirDetallePDF", ReplyAction="*")]
        System.Threading.Tasks.Task<HistorialTH.wsObservatorio.escribirDetallePDFResponse> escribirDetallePDFAsync(HistorialTH.wsObservatorio.escribirDetallePDFRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class escribirDetallePDFIndexRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="escribirDetallePDFIndex", Namespace="http://tempuri.org/", Order=0)]
        public HistorialTH.wsObservatorio.escribirDetallePDFIndexRequestBody Body;
        
        public escribirDetallePDFIndexRequest() {
        }
        
        public escribirDetallePDFIndexRequest(HistorialTH.wsObservatorio.escribirDetallePDFIndexRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class escribirDetallePDFIndexRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idRegistro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mapPath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string varSession;
        
        public escribirDetallePDFIndexRequestBody() {
        }
        
        public escribirDetallePDFIndexRequestBody(int idRegistro, string mapPath, string varSession) {
            this.idRegistro = idRegistro;
            this.mapPath = mapPath;
            this.varSession = varSession;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class escribirDetallePDFIndexResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="escribirDetallePDFIndexResponse", Namespace="http://tempuri.org/", Order=0)]
        public HistorialTH.wsObservatorio.escribirDetallePDFIndexResponseBody Body;
        
        public escribirDetallePDFIndexResponse() {
        }
        
        public escribirDetallePDFIndexResponse(HistorialTH.wsObservatorio.escribirDetallePDFIndexResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class escribirDetallePDFIndexResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string escribirDetallePDFIndexResult;
        
        public escribirDetallePDFIndexResponseBody() {
        }
        
        public escribirDetallePDFIndexResponseBody(string escribirDetallePDFIndexResult) {
            this.escribirDetallePDFIndexResult = escribirDetallePDFIndexResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class escribirDetallePDFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="escribirDetallePDF", Namespace="http://tempuri.org/", Order=0)]
        public HistorialTH.wsObservatorio.escribirDetallePDFRequestBody Body;
        
        public escribirDetallePDFRequest() {
        }
        
        public escribirDetallePDFRequest(HistorialTH.wsObservatorio.escribirDetallePDFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class escribirDetallePDFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HistorialTH.wsObservatorio.Ent_Reporte_OBSERVATORIO elementListado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Color;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mapPath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string varSession;
        
        public escribirDetallePDFRequestBody() {
        }
        
        public escribirDetallePDFRequestBody(HistorialTH.wsObservatorio.Ent_Reporte_OBSERVATORIO elementListado, string Color, string mapPath, string varSession) {
            this.elementListado = elementListado;
            this.Color = Color;
            this.mapPath = mapPath;
            this.varSession = varSession;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class escribirDetallePDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="escribirDetallePDFResponse", Namespace="http://tempuri.org/", Order=0)]
        public HistorialTH.wsObservatorio.escribirDetallePDFResponseBody Body;
        
        public escribirDetallePDFResponse() {
        }
        
        public escribirDetallePDFResponse(HistorialTH.wsObservatorio.escribirDetallePDFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class escribirDetallePDFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string escribirDetallePDFResult;
        
        public escribirDetallePDFResponseBody() {
        }
        
        public escribirDetallePDFResponseBody(string escribirDetallePDFResult) {
            this.escribirDetallePDFResult = escribirDetallePDFResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSObservatorioSoapChannel : HistorialTH.wsObservatorio.WSObservatorioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSObservatorioSoapClient : System.ServiceModel.ClientBase<HistorialTH.wsObservatorio.WSObservatorioSoap>, HistorialTH.wsObservatorio.WSObservatorioSoap {
        
        public WSObservatorioSoapClient() {
        }
        
        public WSObservatorioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSObservatorioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSObservatorioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSObservatorioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HistorialTH.wsObservatorio.escribirDetallePDFIndexResponse HistorialTH.wsObservatorio.WSObservatorioSoap.escribirDetallePDFIndex(HistorialTH.wsObservatorio.escribirDetallePDFIndexRequest request) {
            return base.Channel.escribirDetallePDFIndex(request);
        }
        
        public string escribirDetallePDFIndex(int idRegistro, string mapPath, string varSession) {
            HistorialTH.wsObservatorio.escribirDetallePDFIndexRequest inValue = new HistorialTH.wsObservatorio.escribirDetallePDFIndexRequest();
            inValue.Body = new HistorialTH.wsObservatorio.escribirDetallePDFIndexRequestBody();
            inValue.Body.idRegistro = idRegistro;
            inValue.Body.mapPath = mapPath;
            inValue.Body.varSession = varSession;
            HistorialTH.wsObservatorio.escribirDetallePDFIndexResponse retVal = ((HistorialTH.wsObservatorio.WSObservatorioSoap)(this)).escribirDetallePDFIndex(inValue);
            return retVal.Body.escribirDetallePDFIndexResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HistorialTH.wsObservatorio.escribirDetallePDFIndexResponse> HistorialTH.wsObservatorio.WSObservatorioSoap.escribirDetallePDFIndexAsync(HistorialTH.wsObservatorio.escribirDetallePDFIndexRequest request) {
            return base.Channel.escribirDetallePDFIndexAsync(request);
        }
        
        public System.Threading.Tasks.Task<HistorialTH.wsObservatorio.escribirDetallePDFIndexResponse> escribirDetallePDFIndexAsync(int idRegistro, string mapPath, string varSession) {
            HistorialTH.wsObservatorio.escribirDetallePDFIndexRequest inValue = new HistorialTH.wsObservatorio.escribirDetallePDFIndexRequest();
            inValue.Body = new HistorialTH.wsObservatorio.escribirDetallePDFIndexRequestBody();
            inValue.Body.idRegistro = idRegistro;
            inValue.Body.mapPath = mapPath;
            inValue.Body.varSession = varSession;
            return ((HistorialTH.wsObservatorio.WSObservatorioSoap)(this)).escribirDetallePDFIndexAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HistorialTH.wsObservatorio.escribirDetallePDFResponse HistorialTH.wsObservatorio.WSObservatorioSoap.escribirDetallePDF(HistorialTH.wsObservatorio.escribirDetallePDFRequest request) {
            return base.Channel.escribirDetallePDF(request);
        }
        
        public string escribirDetallePDF(HistorialTH.wsObservatorio.Ent_Reporte_OBSERVATORIO elementListado, string Color, string mapPath, string varSession) {
            HistorialTH.wsObservatorio.escribirDetallePDFRequest inValue = new HistorialTH.wsObservatorio.escribirDetallePDFRequest();
            inValue.Body = new HistorialTH.wsObservatorio.escribirDetallePDFRequestBody();
            inValue.Body.elementListado = elementListado;
            inValue.Body.Color = Color;
            inValue.Body.mapPath = mapPath;
            inValue.Body.varSession = varSession;
            HistorialTH.wsObservatorio.escribirDetallePDFResponse retVal = ((HistorialTH.wsObservatorio.WSObservatorioSoap)(this)).escribirDetallePDF(inValue);
            return retVal.Body.escribirDetallePDFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HistorialTH.wsObservatorio.escribirDetallePDFResponse> HistorialTH.wsObservatorio.WSObservatorioSoap.escribirDetallePDFAsync(HistorialTH.wsObservatorio.escribirDetallePDFRequest request) {
            return base.Channel.escribirDetallePDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<HistorialTH.wsObservatorio.escribirDetallePDFResponse> escribirDetallePDFAsync(HistorialTH.wsObservatorio.Ent_Reporte_OBSERVATORIO elementListado, string Color, string mapPath, string varSession) {
            HistorialTH.wsObservatorio.escribirDetallePDFRequest inValue = new HistorialTH.wsObservatorio.escribirDetallePDFRequest();
            inValue.Body = new HistorialTH.wsObservatorio.escribirDetallePDFRequestBody();
            inValue.Body.elementListado = elementListado;
            inValue.Body.Color = Color;
            inValue.Body.mapPath = mapPath;
            inValue.Body.varSession = varSession;
            return ((HistorialTH.wsObservatorio.WSObservatorioSoap)(this)).escribirDetallePDFAsync(inValue);
        }
    }
}
