//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Observatorio.obsWSObservatorio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ent_Reporte_OBSERVATORIO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Observatorio.obsWSObservatorio.Ent_Reporte_OBSERVATORIO[]))]
    public partial class Ent_Reporte_OBSERVATORIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_REGISTROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TITULARField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUM_THABILITANTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MODALIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UBICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REGIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROVINCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DISTRITOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUM_POAField;
        
        private decimal VOLUMENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RES_APROBACION_POAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RES_REFORMULA_POAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VIGENCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZAFRAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COLORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TRAZAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string INF_FALSAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ARBOLES_INEXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CAMBIO_USOField;
        
        private decimal AREA_CAMBIO_USOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_RESODIRECField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUM_RESOLUCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_RESOLUCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object MEDIDA_CAUTELARField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object CADUCIDADField;
        
        private decimal MONTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object IMPROCEDENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object FUNDADAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object FUNDADA_PARTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object INFUNDADAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string INCISOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESC_ESPECIESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_REPORTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PARAMETROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHA_INICIO_THField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHA_TERMINO_THField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHA_SUPERVISION_INICIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHA_SUPERVISION_TERMINOField;
        
        private int NUM_ARBOLES_INEXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_INFORMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_ENCIENTIFICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOM_CIENTIFICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBRE_COMUNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OBSERVACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NIVEL_RIESGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_NIVEL_RIESGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_RIESGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DES_TIPO_RIESGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OBSERVACION_RIESGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHA_INGRESOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PORCENT_BEXTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PORCENT_AUTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PORCENT_INEXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_ITIPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_THABILITANTEField;
        
        private int NUM_POA_INTField;
        
        private decimal VOLUMEN_BEXTField;
        
        private decimal VOLUMEN_AUTField;
        
        private int NUM_ARB_MUESTRAField;
        
        private int NUM_ARB_INEXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FECHA_BEXTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string INFRACCIONESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TEXTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object RD_MOSTRAR_INCISOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TEXTO_CADUCAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Observatorio.obsWSObservatorio.Ent_Reporte_OBSERVATORIO[] List_Resumen_ROJOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Observatorio.obsWSObservatorio.Ent_Reporte_OBSERVATORIO[] List_Resumen_AMBARField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Observatorio.obsWSObservatorio.Ent_Reporte_OBSERVATORIO[] List_Resumen_VERDEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Observatorio.obsWSObservatorio.Ent_Reporte_OBSERVATORIO[] List_Injus_InfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Observatorio.obsWSObservatorio.Ent_Reporte_OBSERVATORIO[] List_ResolucionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Observatorio.obsWSObservatorio.Ent_Reporte_OBSERVATORIO[] List_Detalle_TitularField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_REGISTRO {
            get {
                return this.ID_REGISTROField;
            }
            set {
                if ((this.ID_REGISTROField.Equals(value) != true)) {
                    this.ID_REGISTROField = value;
                    this.RaisePropertyChanged("ID_REGISTRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TITULAR {
            get {
                return this.TITULARField;
            }
            set {
                if ((object.ReferenceEquals(this.TITULARField, value) != true)) {
                    this.TITULARField = value;
                    this.RaisePropertyChanged("TITULAR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NUM_THABILITANTE {
            get {
                return this.NUM_THABILITANTEField;
            }
            set {
                if ((object.ReferenceEquals(this.NUM_THABILITANTEField, value) != true)) {
                    this.NUM_THABILITANTEField = value;
                    this.RaisePropertyChanged("NUM_THABILITANTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MODALIDAD {
            get {
                return this.MODALIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.MODALIDADField, value) != true)) {
                    this.MODALIDADField = value;
                    this.RaisePropertyChanged("MODALIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UBICACION {
            get {
                return this.UBICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.UBICACIONField, value) != true)) {
                    this.UBICACIONField = value;
                    this.RaisePropertyChanged("UBICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string REGION {
            get {
                return this.REGIONField;
            }
            set {
                if ((object.ReferenceEquals(this.REGIONField, value) != true)) {
                    this.REGIONField = value;
                    this.RaisePropertyChanged("REGION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string PROVINCIA {
            get {
                return this.PROVINCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.PROVINCIAField, value) != true)) {
                    this.PROVINCIAField = value;
                    this.RaisePropertyChanged("PROVINCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string DISTRITO {
            get {
                return this.DISTRITOField;
            }
            set {
                if ((object.ReferenceEquals(this.DISTRITOField, value) != true)) {
                    this.DISTRITOField = value;
                    this.RaisePropertyChanged("DISTRITO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string NUM_POA {
            get {
                return this.NUM_POAField;
            }
            set {
                if ((object.ReferenceEquals(this.NUM_POAField, value) != true)) {
                    this.NUM_POAField = value;
                    this.RaisePropertyChanged("NUM_POA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public decimal VOLUMEN {
            get {
                return this.VOLUMENField;
            }
            set {
                if ((this.VOLUMENField.Equals(value) != true)) {
                    this.VOLUMENField = value;
                    this.RaisePropertyChanged("VOLUMEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string RES_APROBACION_POA {
            get {
                return this.RES_APROBACION_POAField;
            }
            set {
                if ((object.ReferenceEquals(this.RES_APROBACION_POAField, value) != true)) {
                    this.RES_APROBACION_POAField = value;
                    this.RaisePropertyChanged("RES_APROBACION_POA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string RES_REFORMULA_POA {
            get {
                return this.RES_REFORMULA_POAField;
            }
            set {
                if ((object.ReferenceEquals(this.RES_REFORMULA_POAField, value) != true)) {
                    this.RES_REFORMULA_POAField = value;
                    this.RaisePropertyChanged("RES_REFORMULA_POA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string VIGENCIA {
            get {
                return this.VIGENCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.VIGENCIAField, value) != true)) {
                    this.VIGENCIAField = value;
                    this.RaisePropertyChanged("VIGENCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string ZAFRA {
            get {
                return this.ZAFRAField;
            }
            set {
                if ((object.ReferenceEquals(this.ZAFRAField, value) != true)) {
                    this.ZAFRAField = value;
                    this.RaisePropertyChanged("ZAFRA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string COLOR {
            get {
                return this.COLORField;
            }
            set {
                if ((object.ReferenceEquals(this.COLORField, value) != true)) {
                    this.COLORField = value;
                    this.RaisePropertyChanged("COLOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string TRAZA {
            get {
                return this.TRAZAField;
            }
            set {
                if ((object.ReferenceEquals(this.TRAZAField, value) != true)) {
                    this.TRAZAField = value;
                    this.RaisePropertyChanged("TRAZA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string INF_FALSA {
            get {
                return this.INF_FALSAField;
            }
            set {
                if ((object.ReferenceEquals(this.INF_FALSAField, value) != true)) {
                    this.INF_FALSAField = value;
                    this.RaisePropertyChanged("INF_FALSA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string ARBOLES_INEX {
            get {
                return this.ARBOLES_INEXField;
            }
            set {
                if ((object.ReferenceEquals(this.ARBOLES_INEXField, value) != true)) {
                    this.ARBOLES_INEXField = value;
                    this.RaisePropertyChanged("ARBOLES_INEX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string CAMBIO_USO {
            get {
                return this.CAMBIO_USOField;
            }
            set {
                if ((object.ReferenceEquals(this.CAMBIO_USOField, value) != true)) {
                    this.CAMBIO_USOField = value;
                    this.RaisePropertyChanged("CAMBIO_USO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public decimal AREA_CAMBIO_USO {
            get {
                return this.AREA_CAMBIO_USOField;
            }
            set {
                if ((this.AREA_CAMBIO_USOField.Equals(value) != true)) {
                    this.AREA_CAMBIO_USOField = value;
                    this.RaisePropertyChanged("AREA_CAMBIO_USO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADOField, value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string COD_RESODIREC {
            get {
                return this.COD_RESODIRECField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_RESODIRECField, value) != true)) {
                    this.COD_RESODIRECField = value;
                    this.RaisePropertyChanged("COD_RESODIREC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string NUM_RESOLUCION {
            get {
                return this.NUM_RESOLUCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.NUM_RESOLUCIONField, value) != true)) {
                    this.NUM_RESOLUCIONField = value;
                    this.RaisePropertyChanged("NUM_RESOLUCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string TIPO_RESOLUCION {
            get {
                return this.TIPO_RESOLUCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_RESOLUCIONField, value) != true)) {
                    this.TIPO_RESOLUCIONField = value;
                    this.RaisePropertyChanged("TIPO_RESOLUCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public object MEDIDA_CAUTELAR {
            get {
                return this.MEDIDA_CAUTELARField;
            }
            set {
                if ((object.ReferenceEquals(this.MEDIDA_CAUTELARField, value) != true)) {
                    this.MEDIDA_CAUTELARField = value;
                    this.RaisePropertyChanged("MEDIDA_CAUTELAR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public object CADUCIDAD {
            get {
                return this.CADUCIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.CADUCIDADField, value) != true)) {
                    this.CADUCIDADField = value;
                    this.RaisePropertyChanged("CADUCIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=26)]
        public decimal MONTO {
            get {
                return this.MONTOField;
            }
            set {
                if ((this.MONTOField.Equals(value) != true)) {
                    this.MONTOField = value;
                    this.RaisePropertyChanged("MONTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public object IMPROCEDENTE {
            get {
                return this.IMPROCEDENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.IMPROCEDENTEField, value) != true)) {
                    this.IMPROCEDENTEField = value;
                    this.RaisePropertyChanged("IMPROCEDENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public object FUNDADA {
            get {
                return this.FUNDADAField;
            }
            set {
                if ((object.ReferenceEquals(this.FUNDADAField, value) != true)) {
                    this.FUNDADAField = value;
                    this.RaisePropertyChanged("FUNDADA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public object FUNDADA_PARTE {
            get {
                return this.FUNDADA_PARTEField;
            }
            set {
                if ((object.ReferenceEquals(this.FUNDADA_PARTEField, value) != true)) {
                    this.FUNDADA_PARTEField = value;
                    this.RaisePropertyChanged("FUNDADA_PARTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public object INFUNDADA {
            get {
                return this.INFUNDADAField;
            }
            set {
                if ((object.ReferenceEquals(this.INFUNDADAField, value) != true)) {
                    this.INFUNDADAField = value;
                    this.RaisePropertyChanged("INFUNDADA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string INCISO {
            get {
                return this.INCISOField;
            }
            set {
                if ((object.ReferenceEquals(this.INCISOField, value) != true)) {
                    this.INCISOField = value;
                    this.RaisePropertyChanged("INCISO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string DESC_ESPECIES {
            get {
                return this.DESC_ESPECIESField;
            }
            set {
                if ((object.ReferenceEquals(this.DESC_ESPECIESField, value) != true)) {
                    this.DESC_ESPECIESField = value;
                    this.RaisePropertyChanged("DESC_ESPECIES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string TIPO_REPORTE {
            get {
                return this.TIPO_REPORTEField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_REPORTEField, value) != true)) {
                    this.TIPO_REPORTEField = value;
                    this.RaisePropertyChanged("TIPO_REPORTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string PARAMETRO {
            get {
                return this.PARAMETROField;
            }
            set {
                if ((object.ReferenceEquals(this.PARAMETROField, value) != true)) {
                    this.PARAMETROField = value;
                    this.RaisePropertyChanged("PARAMETRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public string FECHA {
            get {
                return this.FECHAField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHAField, value) != true)) {
                    this.FECHAField = value;
                    this.RaisePropertyChanged("FECHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public string FECHA_INICIO_TH {
            get {
                return this.FECHA_INICIO_THField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHA_INICIO_THField, value) != true)) {
                    this.FECHA_INICIO_THField = value;
                    this.RaisePropertyChanged("FECHA_INICIO_TH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public string FECHA_TERMINO_TH {
            get {
                return this.FECHA_TERMINO_THField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHA_TERMINO_THField, value) != true)) {
                    this.FECHA_TERMINO_THField = value;
                    this.RaisePropertyChanged("FECHA_TERMINO_TH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=38)]
        public string FECHA_SUPERVISION_INICIO {
            get {
                return this.FECHA_SUPERVISION_INICIOField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHA_SUPERVISION_INICIOField, value) != true)) {
                    this.FECHA_SUPERVISION_INICIOField = value;
                    this.RaisePropertyChanged("FECHA_SUPERVISION_INICIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string FECHA_SUPERVISION_TERMINO {
            get {
                return this.FECHA_SUPERVISION_TERMINOField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHA_SUPERVISION_TERMINOField, value) != true)) {
                    this.FECHA_SUPERVISION_TERMINOField = value;
                    this.RaisePropertyChanged("FECHA_SUPERVISION_TERMINO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=40)]
        public int NUM_ARBOLES_INEX {
            get {
                return this.NUM_ARBOLES_INEXField;
            }
            set {
                if ((this.NUM_ARBOLES_INEXField.Equals(value) != true)) {
                    this.NUM_ARBOLES_INEXField = value;
                    this.RaisePropertyChanged("NUM_ARBOLES_INEX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=41)]
        public string COD_INFORME {
            get {
                return this.COD_INFORMEField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_INFORMEField, value) != true)) {
                    this.COD_INFORMEField = value;
                    this.RaisePropertyChanged("COD_INFORME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public string COD_ENCIENTIFICO {
            get {
                return this.COD_ENCIENTIFICOField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_ENCIENTIFICOField, value) != true)) {
                    this.COD_ENCIENTIFICOField = value;
                    this.RaisePropertyChanged("COD_ENCIENTIFICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public string NOM_CIENTIFICO {
            get {
                return this.NOM_CIENTIFICOField;
            }
            set {
                if ((object.ReferenceEquals(this.NOM_CIENTIFICOField, value) != true)) {
                    this.NOM_CIENTIFICOField = value;
                    this.RaisePropertyChanged("NOM_CIENTIFICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=44)]
        public string NOMBRE_COMUN {
            get {
                return this.NOMBRE_COMUNField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBRE_COMUNField, value) != true)) {
                    this.NOMBRE_COMUNField = value;
                    this.RaisePropertyChanged("NOMBRE_COMUN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public string OBSERVACION {
            get {
                return this.OBSERVACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.OBSERVACIONField, value) != true)) {
                    this.OBSERVACIONField = value;
                    this.RaisePropertyChanged("OBSERVACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=46)]
        public string NIVEL_RIESGO {
            get {
                return this.NIVEL_RIESGOField;
            }
            set {
                if ((object.ReferenceEquals(this.NIVEL_RIESGOField, value) != true)) {
                    this.NIVEL_RIESGOField = value;
                    this.RaisePropertyChanged("NIVEL_RIESGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=47)]
        public string DES_NIVEL_RIESGO {
            get {
                return this.DES_NIVEL_RIESGOField;
            }
            set {
                if ((object.ReferenceEquals(this.DES_NIVEL_RIESGOField, value) != true)) {
                    this.DES_NIVEL_RIESGOField = value;
                    this.RaisePropertyChanged("DES_NIVEL_RIESGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=48)]
        public string TIPO_RIESGO {
            get {
                return this.TIPO_RIESGOField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_RIESGOField, value) != true)) {
                    this.TIPO_RIESGOField = value;
                    this.RaisePropertyChanged("TIPO_RIESGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=49)]
        public string DES_TIPO_RIESGO {
            get {
                return this.DES_TIPO_RIESGOField;
            }
            set {
                if ((object.ReferenceEquals(this.DES_TIPO_RIESGOField, value) != true)) {
                    this.DES_TIPO_RIESGOField = value;
                    this.RaisePropertyChanged("DES_TIPO_RIESGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=50)]
        public string OBSERVACION_RIESGO {
            get {
                return this.OBSERVACION_RIESGOField;
            }
            set {
                if ((object.ReferenceEquals(this.OBSERVACION_RIESGOField, value) != true)) {
                    this.OBSERVACION_RIESGOField = value;
                    this.RaisePropertyChanged("OBSERVACION_RIESGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=51)]
        public string FECHA_INGRESO {
            get {
                return this.FECHA_INGRESOField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHA_INGRESOField, value) != true)) {
                    this.FECHA_INGRESOField = value;
                    this.RaisePropertyChanged("FECHA_INGRESO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=52)]
        public string PORCENT_BEXT {
            get {
                return this.PORCENT_BEXTField;
            }
            set {
                if ((object.ReferenceEquals(this.PORCENT_BEXTField, value) != true)) {
                    this.PORCENT_BEXTField = value;
                    this.RaisePropertyChanged("PORCENT_BEXT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=53)]
        public string PORCENT_AUT {
            get {
                return this.PORCENT_AUTField;
            }
            set {
                if ((object.ReferenceEquals(this.PORCENT_AUTField, value) != true)) {
                    this.PORCENT_AUTField = value;
                    this.RaisePropertyChanged("PORCENT_AUT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=54)]
        public string PORCENT_INEX {
            get {
                return this.PORCENT_INEXField;
            }
            set {
                if ((object.ReferenceEquals(this.PORCENT_INEXField, value) != true)) {
                    this.PORCENT_INEXField = value;
                    this.RaisePropertyChanged("PORCENT_INEX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=55)]
        public string COD_ITIPO {
            get {
                return this.COD_ITIPOField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_ITIPOField, value) != true)) {
                    this.COD_ITIPOField = value;
                    this.RaisePropertyChanged("COD_ITIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=56)]
        public string COD_THABILITANTE {
            get {
                return this.COD_THABILITANTEField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_THABILITANTEField, value) != true)) {
                    this.COD_THABILITANTEField = value;
                    this.RaisePropertyChanged("COD_THABILITANTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=57)]
        public int NUM_POA_INT {
            get {
                return this.NUM_POA_INTField;
            }
            set {
                if ((this.NUM_POA_INTField.Equals(value) != true)) {
                    this.NUM_POA_INTField = value;
                    this.RaisePropertyChanged("NUM_POA_INT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=58)]
        public decimal VOLUMEN_BEXT {
            get {
                return this.VOLUMEN_BEXTField;
            }
            set {
                if ((this.VOLUMEN_BEXTField.Equals(value) != true)) {
                    this.VOLUMEN_BEXTField = value;
                    this.RaisePropertyChanged("VOLUMEN_BEXT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=59)]
        public decimal VOLUMEN_AUT {
            get {
                return this.VOLUMEN_AUTField;
            }
            set {
                if ((this.VOLUMEN_AUTField.Equals(value) != true)) {
                    this.VOLUMEN_AUTField = value;
                    this.RaisePropertyChanged("VOLUMEN_AUT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=60)]
        public int NUM_ARB_MUESTRA {
            get {
                return this.NUM_ARB_MUESTRAField;
            }
            set {
                if ((this.NUM_ARB_MUESTRAField.Equals(value) != true)) {
                    this.NUM_ARB_MUESTRAField = value;
                    this.RaisePropertyChanged("NUM_ARB_MUESTRA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=61)]
        public int NUM_ARB_INEX {
            get {
                return this.NUM_ARB_INEXField;
            }
            set {
                if ((this.NUM_ARB_INEXField.Equals(value) != true)) {
                    this.NUM_ARB_INEXField = value;
                    this.RaisePropertyChanged("NUM_ARB_INEX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=62)]
        public string FECHA_BEXT {
            get {
                return this.FECHA_BEXTField;
            }
            set {
                if ((object.ReferenceEquals(this.FECHA_BEXTField, value) != true)) {
                    this.FECHA_BEXTField = value;
                    this.RaisePropertyChanged("FECHA_BEXT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=63)]
        public string INFRACCIONES {
            get {
                return this.INFRACCIONESField;
            }
            set {
                if ((object.ReferenceEquals(this.INFRACCIONESField, value) != true)) {
                    this.INFRACCIONESField = value;
                    this.RaisePropertyChanged("INFRACCIONES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=64)]
        public string TEXTO {
            get {
                return this.TEXTOField;
            }
            set {
                if ((object.ReferenceEquals(this.TEXTOField, value) != true)) {
                    this.TEXTOField = value;
                    this.RaisePropertyChanged("TEXTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=65)]
        public object RD_MOSTRAR_INCISOS {
            get {
                return this.RD_MOSTRAR_INCISOSField;
            }
            set {
                if ((object.ReferenceEquals(this.RD_MOSTRAR_INCISOSField, value) != true)) {
                    this.RD_MOSTRAR_INCISOSField = value;
                    this.RaisePropertyChanged("RD_MOSTRAR_INCISOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=66)]
        public string TEXTO_CADUCA {
            get {
                return this.TEXTO_CADUCAField;
            }
            set {
                if ((object.ReferenceEquals(this.TEXTO_CADUCAField, value) != true)) {
                    this.TEXTO_CADUCAField = value;
                    this.RaisePropertyChanged("TEXTO_CADUCA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=67)]
        public Observatorio.obsWSObservatorio.Ent_Reporte_OBSERVATORIO[] List_Resumen_ROJO {
            get {
                return this.List_Resumen_ROJOField;
            }
            set {
                if ((object.ReferenceEquals(this.List_Resumen_ROJOField, value) != true)) {
                    this.List_Resumen_ROJOField = value;
                    this.RaisePropertyChanged("List_Resumen_ROJO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=68)]
        public Observatorio.obsWSObservatorio.Ent_Reporte_OBSERVATORIO[] List_Resumen_AMBAR {
            get {
                return this.List_Resumen_AMBARField;
            }
            set {
                if ((object.ReferenceEquals(this.List_Resumen_AMBARField, value) != true)) {
                    this.List_Resumen_AMBARField = value;
                    this.RaisePropertyChanged("List_Resumen_AMBAR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=69)]
        public Observatorio.obsWSObservatorio.Ent_Reporte_OBSERVATORIO[] List_Resumen_VERDE {
            get {
                return this.List_Resumen_VERDEField;
            }
            set {
                if ((object.ReferenceEquals(this.List_Resumen_VERDEField, value) != true)) {
                    this.List_Resumen_VERDEField = value;
                    this.RaisePropertyChanged("List_Resumen_VERDE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=70)]
        public Observatorio.obsWSObservatorio.Ent_Reporte_OBSERVATORIO[] List_Injus_Inf {
            get {
                return this.List_Injus_InfField;
            }
            set {
                if ((object.ReferenceEquals(this.List_Injus_InfField, value) != true)) {
                    this.List_Injus_InfField = value;
                    this.RaisePropertyChanged("List_Injus_Inf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=71)]
        public Observatorio.obsWSObservatorio.Ent_Reporte_OBSERVATORIO[] List_Resoluciones {
            get {
                return this.List_ResolucionesField;
            }
            set {
                if ((object.ReferenceEquals(this.List_ResolucionesField, value) != true)) {
                    this.List_ResolucionesField = value;
                    this.RaisePropertyChanged("List_Resoluciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=72)]
        public Observatorio.obsWSObservatorio.Ent_Reporte_OBSERVATORIO[] List_Detalle_Titular {
            get {
                return this.List_Detalle_TitularField;
            }
            set {
                if ((object.ReferenceEquals(this.List_Detalle_TitularField, value) != true)) {
                    this.List_Detalle_TitularField = value;
                    this.RaisePropertyChanged("List_Detalle_Titular");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="obsWSObservatorio.WSObservatorioSoap")]
    public interface WSObservatorioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento mapPath del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/escribirDetallePDFIndex", ReplyAction="*")]
        Observatorio.obsWSObservatorio.escribirDetallePDFIndexResponse escribirDetallePDFIndex(Observatorio.obsWSObservatorio.escribirDetallePDFIndexRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/escribirDetallePDFIndex", ReplyAction="*")]
        System.Threading.Tasks.Task<Observatorio.obsWSObservatorio.escribirDetallePDFIndexResponse> escribirDetallePDFIndexAsync(Observatorio.obsWSObservatorio.escribirDetallePDFIndexRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento elementoObs del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/escribirDetallePDFAntiguo", ReplyAction="*")]
        Observatorio.obsWSObservatorio.escribirDetallePDFAntiguoResponse escribirDetallePDFAntiguo(Observatorio.obsWSObservatorio.escribirDetallePDFAntiguoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/escribirDetallePDFAntiguo", ReplyAction="*")]
        System.Threading.Tasks.Task<Observatorio.obsWSObservatorio.escribirDetallePDFAntiguoResponse> escribirDetallePDFAntiguoAsync(Observatorio.obsWSObservatorio.escribirDetallePDFAntiguoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento elementListado del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/escribirDetallePDF", ReplyAction="*")]
        Observatorio.obsWSObservatorio.escribirDetallePDFResponse escribirDetallePDF(Observatorio.obsWSObservatorio.escribirDetallePDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/escribirDetallePDF", ReplyAction="*")]
        System.Threading.Tasks.Task<Observatorio.obsWSObservatorio.escribirDetallePDFResponse> escribirDetallePDFAsync(Observatorio.obsWSObservatorio.escribirDetallePDFRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class escribirDetallePDFIndexRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="escribirDetallePDFIndex", Namespace="http://tempuri.org/", Order=0)]
        public Observatorio.obsWSObservatorio.escribirDetallePDFIndexRequestBody Body;
        
        public escribirDetallePDFIndexRequest() {
        }
        
        public escribirDetallePDFIndexRequest(Observatorio.obsWSObservatorio.escribirDetallePDFIndexRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class escribirDetallePDFIndexRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idRegistro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mapPath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string varSession;
        
        public escribirDetallePDFIndexRequestBody() {
        }
        
        public escribirDetallePDFIndexRequestBody(int idRegistro, string mapPath, string varSession) {
            this.idRegistro = idRegistro;
            this.mapPath = mapPath;
            this.varSession = varSession;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class escribirDetallePDFIndexResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="escribirDetallePDFIndexResponse", Namespace="http://tempuri.org/", Order=0)]
        public Observatorio.obsWSObservatorio.escribirDetallePDFIndexResponseBody Body;
        
        public escribirDetallePDFIndexResponse() {
        }
        
        public escribirDetallePDFIndexResponse(Observatorio.obsWSObservatorio.escribirDetallePDFIndexResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class escribirDetallePDFIndexResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string escribirDetallePDFIndexResult;
        
        public escribirDetallePDFIndexResponseBody() {
        }
        
        public escribirDetallePDFIndexResponseBody(string escribirDetallePDFIndexResult) {
            this.escribirDetallePDFIndexResult = escribirDetallePDFIndexResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class escribirDetallePDFAntiguoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="escribirDetallePDFAntiguo", Namespace="http://tempuri.org/", Order=0)]
        public Observatorio.obsWSObservatorio.escribirDetallePDFAntiguoRequestBody Body;
        
        public escribirDetallePDFAntiguoRequest() {
        }
        
        public escribirDetallePDFAntiguoRequest(Observatorio.obsWSObservatorio.escribirDetallePDFAntiguoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class escribirDetallePDFAntiguoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Observatorio.obsWSObservatorio.Ent_Reporte_OBSERVATORIO elementoObs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Color;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mapPath;
        
        public escribirDetallePDFAntiguoRequestBody() {
        }
        
        public escribirDetallePDFAntiguoRequestBody(Observatorio.obsWSObservatorio.Ent_Reporte_OBSERVATORIO elementoObs, string Color, string mapPath) {
            this.elementoObs = elementoObs;
            this.Color = Color;
            this.mapPath = mapPath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class escribirDetallePDFAntiguoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="escribirDetallePDFAntiguoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Observatorio.obsWSObservatorio.escribirDetallePDFAntiguoResponseBody Body;
        
        public escribirDetallePDFAntiguoResponse() {
        }
        
        public escribirDetallePDFAntiguoResponse(Observatorio.obsWSObservatorio.escribirDetallePDFAntiguoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class escribirDetallePDFAntiguoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string escribirDetallePDFAntiguoResult;
        
        public escribirDetallePDFAntiguoResponseBody() {
        }
        
        public escribirDetallePDFAntiguoResponseBody(string escribirDetallePDFAntiguoResult) {
            this.escribirDetallePDFAntiguoResult = escribirDetallePDFAntiguoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class escribirDetallePDFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="escribirDetallePDF", Namespace="http://tempuri.org/", Order=0)]
        public Observatorio.obsWSObservatorio.escribirDetallePDFRequestBody Body;
        
        public escribirDetallePDFRequest() {
        }
        
        public escribirDetallePDFRequest(Observatorio.obsWSObservatorio.escribirDetallePDFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class escribirDetallePDFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Observatorio.obsWSObservatorio.Ent_Reporte_OBSERVATORIO elementListado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Color;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mapPath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string varSession;
        
        public escribirDetallePDFRequestBody() {
        }
        
        public escribirDetallePDFRequestBody(Observatorio.obsWSObservatorio.Ent_Reporte_OBSERVATORIO elementListado, string Color, string mapPath, string varSession) {
            this.elementListado = elementListado;
            this.Color = Color;
            this.mapPath = mapPath;
            this.varSession = varSession;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class escribirDetallePDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="escribirDetallePDFResponse", Namespace="http://tempuri.org/", Order=0)]
        public Observatorio.obsWSObservatorio.escribirDetallePDFResponseBody Body;
        
        public escribirDetallePDFResponse() {
        }
        
        public escribirDetallePDFResponse(Observatorio.obsWSObservatorio.escribirDetallePDFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class escribirDetallePDFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string escribirDetallePDFResult;
        
        public escribirDetallePDFResponseBody() {
        }
        
        public escribirDetallePDFResponseBody(string escribirDetallePDFResult) {
            this.escribirDetallePDFResult = escribirDetallePDFResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSObservatorioSoapChannel : Observatorio.obsWSObservatorio.WSObservatorioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSObservatorioSoapClient : System.ServiceModel.ClientBase<Observatorio.obsWSObservatorio.WSObservatorioSoap>, Observatorio.obsWSObservatorio.WSObservatorioSoap {
        
        public WSObservatorioSoapClient() {
        }
        
        public WSObservatorioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSObservatorioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSObservatorioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSObservatorioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Observatorio.obsWSObservatorio.escribirDetallePDFIndexResponse Observatorio.obsWSObservatorio.WSObservatorioSoap.escribirDetallePDFIndex(Observatorio.obsWSObservatorio.escribirDetallePDFIndexRequest request) {
            return base.Channel.escribirDetallePDFIndex(request);
        }
        
        public string escribirDetallePDFIndex(int idRegistro, string mapPath, string varSession) {
            Observatorio.obsWSObservatorio.escribirDetallePDFIndexRequest inValue = new Observatorio.obsWSObservatorio.escribirDetallePDFIndexRequest();
            inValue.Body = new Observatorio.obsWSObservatorio.escribirDetallePDFIndexRequestBody();
            inValue.Body.idRegistro = idRegistro;
            inValue.Body.mapPath = mapPath;
            inValue.Body.varSession = varSession;
            Observatorio.obsWSObservatorio.escribirDetallePDFIndexResponse retVal = ((Observatorio.obsWSObservatorio.WSObservatorioSoap)(this)).escribirDetallePDFIndex(inValue);
            return retVal.Body.escribirDetallePDFIndexResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Observatorio.obsWSObservatorio.escribirDetallePDFIndexResponse> Observatorio.obsWSObservatorio.WSObservatorioSoap.escribirDetallePDFIndexAsync(Observatorio.obsWSObservatorio.escribirDetallePDFIndexRequest request) {
            return base.Channel.escribirDetallePDFIndexAsync(request);
        }
        
        public System.Threading.Tasks.Task<Observatorio.obsWSObservatorio.escribirDetallePDFIndexResponse> escribirDetallePDFIndexAsync(int idRegistro, string mapPath, string varSession) {
            Observatorio.obsWSObservatorio.escribirDetallePDFIndexRequest inValue = new Observatorio.obsWSObservatorio.escribirDetallePDFIndexRequest();
            inValue.Body = new Observatorio.obsWSObservatorio.escribirDetallePDFIndexRequestBody();
            inValue.Body.idRegistro = idRegistro;
            inValue.Body.mapPath = mapPath;
            inValue.Body.varSession = varSession;
            return ((Observatorio.obsWSObservatorio.WSObservatorioSoap)(this)).escribirDetallePDFIndexAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Observatorio.obsWSObservatorio.escribirDetallePDFAntiguoResponse Observatorio.obsWSObservatorio.WSObservatorioSoap.escribirDetallePDFAntiguo(Observatorio.obsWSObservatorio.escribirDetallePDFAntiguoRequest request) {
            return base.Channel.escribirDetallePDFAntiguo(request);
        }
        
        public string escribirDetallePDFAntiguo(Observatorio.obsWSObservatorio.Ent_Reporte_OBSERVATORIO elementoObs, string Color, string mapPath) {
            Observatorio.obsWSObservatorio.escribirDetallePDFAntiguoRequest inValue = new Observatorio.obsWSObservatorio.escribirDetallePDFAntiguoRequest();
            inValue.Body = new Observatorio.obsWSObservatorio.escribirDetallePDFAntiguoRequestBody();
            inValue.Body.elementoObs = elementoObs;
            inValue.Body.Color = Color;
            inValue.Body.mapPath = mapPath;
            Observatorio.obsWSObservatorio.escribirDetallePDFAntiguoResponse retVal = ((Observatorio.obsWSObservatorio.WSObservatorioSoap)(this)).escribirDetallePDFAntiguo(inValue);
            return retVal.Body.escribirDetallePDFAntiguoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Observatorio.obsWSObservatorio.escribirDetallePDFAntiguoResponse> Observatorio.obsWSObservatorio.WSObservatorioSoap.escribirDetallePDFAntiguoAsync(Observatorio.obsWSObservatorio.escribirDetallePDFAntiguoRequest request) {
            return base.Channel.escribirDetallePDFAntiguoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Observatorio.obsWSObservatorio.escribirDetallePDFAntiguoResponse> escribirDetallePDFAntiguoAsync(Observatorio.obsWSObservatorio.Ent_Reporte_OBSERVATORIO elementoObs, string Color, string mapPath) {
            Observatorio.obsWSObservatorio.escribirDetallePDFAntiguoRequest inValue = new Observatorio.obsWSObservatorio.escribirDetallePDFAntiguoRequest();
            inValue.Body = new Observatorio.obsWSObservatorio.escribirDetallePDFAntiguoRequestBody();
            inValue.Body.elementoObs = elementoObs;
            inValue.Body.Color = Color;
            inValue.Body.mapPath = mapPath;
            return ((Observatorio.obsWSObservatorio.WSObservatorioSoap)(this)).escribirDetallePDFAntiguoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Observatorio.obsWSObservatorio.escribirDetallePDFResponse Observatorio.obsWSObservatorio.WSObservatorioSoap.escribirDetallePDF(Observatorio.obsWSObservatorio.escribirDetallePDFRequest request) {
            return base.Channel.escribirDetallePDF(request);
        }
        
        public string escribirDetallePDF(Observatorio.obsWSObservatorio.Ent_Reporte_OBSERVATORIO elementListado, string Color, string mapPath, string varSession) {
            Observatorio.obsWSObservatorio.escribirDetallePDFRequest inValue = new Observatorio.obsWSObservatorio.escribirDetallePDFRequest();
            inValue.Body = new Observatorio.obsWSObservatorio.escribirDetallePDFRequestBody();
            inValue.Body.elementListado = elementListado;
            inValue.Body.Color = Color;
            inValue.Body.mapPath = mapPath;
            inValue.Body.varSession = varSession;
            Observatorio.obsWSObservatorio.escribirDetallePDFResponse retVal = ((Observatorio.obsWSObservatorio.WSObservatorioSoap)(this)).escribirDetallePDF(inValue);
            return retVal.Body.escribirDetallePDFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Observatorio.obsWSObservatorio.escribirDetallePDFResponse> Observatorio.obsWSObservatorio.WSObservatorioSoap.escribirDetallePDFAsync(Observatorio.obsWSObservatorio.escribirDetallePDFRequest request) {
            return base.Channel.escribirDetallePDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<Observatorio.obsWSObservatorio.escribirDetallePDFResponse> escribirDetallePDFAsync(Observatorio.obsWSObservatorio.Ent_Reporte_OBSERVATORIO elementListado, string Color, string mapPath, string varSession) {
            Observatorio.obsWSObservatorio.escribirDetallePDFRequest inValue = new Observatorio.obsWSObservatorio.escribirDetallePDFRequest();
            inValue.Body = new Observatorio.obsWSObservatorio.escribirDetallePDFRequestBody();
            inValue.Body.elementListado = elementListado;
            inValue.Body.Color = Color;
            inValue.Body.mapPath = mapPath;
            inValue.Body.varSession = varSession;
            return ((Observatorio.obsWSObservatorio.WSObservatorioSoap)(this)).escribirDetallePDFAsync(inValue);
        }
    }
}
